# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import RiskCategory


class AssetAnalyticLite(BaseModel):
    vulnerability: "AssetAnalyticLiteVulnerability"
    misconfigurations: "AssetAnalyticLiteMisconfigurations"
    components: "AssetAnalyticLiteComponents"


class AssetAnalyticLiteVulnerability(BaseModel):
    critical: int
    high: int
    medium: int
    low: int


class AssetAnalyticLiteMisconfigurations(BaseModel):
    failed: int
    not_applicable: int = Field(alias="notApplicable")
    passed: int


class AssetAnalyticLiteComponents(BaseModel):
    application: int
    container: int
    device: int
    framework: int
    kernel: int
    kernel_module: int = Field(alias="kernelModule")
    library: int
    os: int
    package: int


class CvssPreferred(BaseModel):
    metric: Optional["CvssPreferredMetric"]


class CvssPreferredMetric(BaseModel):
    cvss_data: Optional["CvssPreferredMetricCvssData"] = Field(alias="cvssData")


class CvssPreferredMetricCvssData(BaseModel):
    base_score: Optional[float] = Field(alias="baseScore")
    base_severity: Optional[str] = Field(alias="baseSeverity")
    vector_string: Optional[str] = Field(alias="vectorString")
    version: Optional[str]


class PageInfoFields(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


class RiskFields(BaseModel):
    category: Optional[RiskCategory]
    score: Optional[float]


AssetAnalyticLite.model_rebuild()
CvssPreferred.model_rebuild()
PageInfoFields.model_rebuild()
RiskFields.model_rebuild()
