# Generated by ariadne-codegen
# Source: ../sdk-artifacts/schema.graphql

from datetime import datetime
from typing import Annotated, Any, Optional

from pydantic import Field, PlainSerializer

from .base_model import BaseModel
from .custom_scalars import serialize_datetime
from .enums import (
    AcrEntityType,
    AcrResourceType,
    ActivityEntityType,
    ArtifactName,
    AssetAnalysisEventSelection,
    AssetCorrelationType,
    AssetGroupsField,
    AssetOverviewRiskCategory,
    AssetOverviewSortField,
    AssetsFilterField,
    AssetsSortField,
    AssetType,
    BinaryProtectionsField,
    CertificatesField,
    CertificateValidityPeriod,
    ComponentType,
    CredentialsField,
    CryptoLibrariesSortField,
    CryptoRemediationStatus,
    CycloneDxVersion,
    DependencyField,
    DependencyGroupByField,
    DependencySortField,
    FieldFilterOperation,
    FilterFieldOperation,
    GroupedDependencyField,
    GroupedDependencySortField,
    HashesField,
    HighProfileCategory,
    HighProfileExploitFilterField,
    HighProfileExploitSortField,
    JiraSetupAction,
    JiraSetupMode,
    LicenseIssuesField,
    LicenseIssuesSortField,
    LicenseIssueStatus,
    ListComponentFilterFieldEnum,
    ListComponentSortField,
    ListFilesFilterFieldEnum,
    ListFilesSortField,
    MisconfigurationsField,
    NewSBOMFindingsSelection,
    NotificationActivityKind,
    NotificationActivityThresholdField,
    NotificationActivityThresholdOperator,
    NotificationConfigurationChannel,
    NotificationConfigurationsField,
    NotificationConfigurationType,
    NotificationField,
    NotificationLogsField,
    NotificationParser,
    NotificationSettingsType,
    NotificationSortField,
    NotificationTimeframe,
    NotificationType,
    OrgUserStatus,
    PrivateKeysField,
    PublicKeysField,
    RemediationResponses,
    RiskCategoryFilter,
    SbomFormat,
    SbomType,
    SecretCategory,
    SecretRemediationStatus,
    SecretSeverity,
    SecretsField,
    SecretType,
    Severity,
    SiftSearchType,
    SortOrder,
    SpdxVersion,
    UserActionEnum,
    UserManagementEventSelection,
    VexJustification,
    VexStatus,
    VulnerabilitiesExploitsSelection,
    VulnerabilitiesSeveritiesSelection,
    VulnerabilityField,
    VulnerabilityOverviewFilterField,
    VulnerabilityOverviewSortField,
    VulnerabilitySortField,
)


class IdentifiedComponentsPreviewInput(BaseModel):
    """Org-level: which component identification methods are enabled.
    Each field corresponds to one method (e.g. symbol index, hashes, signatures).
    Used when fetching or filtering org component data by verification method."""

    symbol_index_enabled: Optional[bool] = Field(
        alias="symbolIndexEnabled", default=None
    )
    kernel_module_enabled: Optional[bool] = Field(
        alias="kernelModuleEnabled", default=None
    )
    curated_hash_enabled: Optional[bool] = Field(
        alias="curatedHashEnabled", default=None
    )
    legacy_hash_enabled: Optional[bool] = Field(alias="legacyHashEnabled", default=None)
    package_manifest_enabled: Optional[bool] = Field(
        alias="packageManifestEnabled", default=None
    )
    signature_enabled: Optional[bool] = Field(alias="signatureEnabled", default=None)
    pe_meta_data_enabled: Optional[bool] = Field(
        alias="peMetaDataEnabled", default=None
    )
    library_version_enabled: Optional[bool] = Field(
        alias="libraryVersionEnabled", default=None
    )
    library_name_enabled: Optional[bool] = Field(
        alias="libraryNameEnabled", default=None
    )
    binary_fingerprint_enabled: Optional[bool] = Field(
        alias="binaryFingerprintEnabled", default=None
    )


class OrgLevelSettingsInput(BaseModel):
    symbol_index_enabled: Optional[bool] = Field(
        alias="symbolIndexEnabled", default=None
    )
    kernel_module_enabled: Optional[bool] = Field(
        alias="kernelModuleEnabled", default=None
    )
    curated_hash_enabled: Optional[bool] = Field(
        alias="curatedHashEnabled", default=None
    )
    legacy_hash_enabled: Optional[bool] = Field(alias="legacyHashEnabled", default=None)
    package_manifest_enabled: Optional[bool] = Field(
        alias="packageManifestEnabled", default=None
    )
    signature_enabled: Optional[bool] = Field(alias="signatureEnabled", default=None)
    pe_meta_data_enabled: Optional[bool] = Field(
        alias="peMetaDataEnabled", default=None
    )
    library_version_enabled: Optional[bool] = Field(
        alias="libraryVersionEnabled", default=None
    )
    library_name_enabled: Optional[bool] = Field(
        alias="libraryNameEnabled", default=None
    )
    binary_fingerprint_enabled: Optional[bool] = Field(
        alias="binaryFingerprintEnabled", default=None
    )
    idle_timout_enabled: bool = Field(alias="idleTimoutEnabled")
    idle_timeout_seconds: Optional[int] = Field(
        alias="idleTimeoutSeconds", default=None
    )
    rise_ai_conversational_gpt_enabled: Optional[bool] = Field(
        alias="riseAiConversationalGptEnabled", default=None
    )
    rise_ai_insights_report_enabled: Optional[bool] = Field(
        alias="riseAiInsightsReportEnabled", default=None
    )


class ListAssetCorrelationsInput(BaseModel):
    composed_asset_id: Optional[str] = Field(alias="composedAssetId", default=None)
    identifier: str
    correlation_type: AssetCorrelationType = Field(alias="correlationType")
    cursor: Optional["Cursor"] = None
    "Cursor-based pagination (Relay-style). Uses the same `Cursor` / page request shape as other data queries."


class BinaryProtectionsInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional["BinaryProtectionsFilter"] = None
    sort: Optional["BinaryProtectionsSort"] = None


class BinaryProtectionsFilter(BaseModel):
    fields: Optional[list[Optional["BinaryProtectionsFilterField"]]] = None


class BinaryProtectionsFilterField(BaseModel):
    field_name: Optional[BinaryProtectionsField] = Field(
        alias="fieldName", default=None
    )
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class BinaryProtectionsSort(BaseModel):
    field: Optional[BinaryProtectionsField] = None
    order: Optional[SortOrder] = None


class CertificatesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional["ListCertificatesFilter"] = None
    sort: Optional["ListCertificatesSort"] = None


class ListCertificatesFilter(BaseModel):
    fields: Optional[list[Optional["ListCertificatesFilterField"]]] = None
    algorithm_type: Optional["StringFilter"] = Field(
        alias="algorithmType", default=None
    )
    is_reachable: Optional[bool] = Field(alias="isReachable", default=None)
    "When true, only certificates marked as reachable (reachability v2)."


class ListCertificatesFilterField(BaseModel):
    field_name: Optional[CertificatesField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class ListCertificatesSort(BaseModel):
    field: Optional[CertificatesField] = None
    order: Optional[SortOrder] = None


class CertificateExternalFiltersInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class CertificateIdentifierInput(BaseModel):
    file_path: str = Field(alias="filePath")
    sha_256: str = Field(alias="sha256")


class RemediateCertificatesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    certificates: list[Optional["CertificateIdentifierInput"]]
    status: CryptoRemediationStatus
    details: Optional[str] = None


class HashesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    filter: Optional["HashesFilter"] = None
    sort: Optional["HashesSort"] = None
    cursor: "Cursor"


class HashesFilter(BaseModel):
    fields: Optional[list[Optional["HashesFieldFilter"]]] = None


class HashesFieldFilter(BaseModel):
    field_name: Optional[HashesField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class HashesSort(BaseModel):
    field: Optional[HashesField] = None
    order: Optional[SortOrder] = None


class CredentialsInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    filter: Optional["CredentialsFilter"] = None
    sort: Optional["CredentialsSort"] = None
    cursor: "Cursor"


class CredentialsFilter(BaseModel):
    fields: Optional[list[Optional["CredentialsFieldFilter"]]] = None


class CredentialsFieldFilter(BaseModel):
    field_name: Optional[CredentialsField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class CredentialsSort(BaseModel):
    field: Optional[CredentialsField] = None
    order: Optional[SortOrder] = None


class ListAssetCryptoLibrariesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional[str] = None
    sort: Optional["ListCryptoLibrariesSort"] = None


class ListCryptoLibrariesSort(BaseModel):
    field: Optional[CryptoLibrariesSortField] = None
    order: Optional[SortOrder] = None


class StringFilter(BaseModel):
    eq: Optional[str] = None
    any: Optional[list[str]] = None
    arr: Optional[list[str]] = None


class BooleanFilter(BaseModel):
    eq: bool


class DateTimeFilter(BaseModel):
    lt: Optional[Annotated[datetime, PlainSerializer(serialize_datetime)]] = None
    "Less Than"
    lte: Optional[Annotated[datetime, PlainSerializer(serialize_datetime)]] = None
    "Less Than or Equal To"
    gt: Optional[Annotated[datetime, PlainSerializer(serialize_datetime)]] = None
    "Greater Than"
    gte: Optional[Annotated[datetime, PlainSerializer(serialize_datetime)]] = None
    "Greater Than or Equal To"


class LicenseIssuesExternalFiltersInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class LicenseIssuesFieldFilter(BaseModel):
    """Field-level filter for license issues free-text search."""

    field_name: LicenseIssuesField = Field(alias="fieldName")
    value: Optional[str] = None
    operation: Optional[FilterFieldOperation] = None


class LicenseIssuesFilter(BaseModel):
    """Filter for license issues.
    Note: lastModified is a dedicated date filter."""

    fields: Optional[list["LicenseIssuesFieldFilter"]] = None
    severity: Optional["StringFilter"] = None
    status: Optional["StringFilter"] = None


class LicenseIssuesSort(BaseModel):
    field: LicenseIssuesSortField
    order: SortOrder


class LicenseIssuesInput(BaseModel):
    """License issues query input."""

    asset_id: str = Field(alias="assetId")
    filter: Optional["LicenseIssuesFilter"] = None
    cursor: Optional["Cursor"] = None
    sort: Optional["LicenseIssuesSort"] = None


class LicenseIssueInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    issue_id: str = Field(alias="issueId")


class RemediateLicenseIssuesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    issue_ids: list[str] = Field(alias="issueIds")
    status: LicenseIssueStatus
    details: Optional[str] = None


class LicenseInput(BaseModel):
    """**Breaking change (no prior deprecation):** `assetId` was added as a required field (`ID!`) on
    2026-01-22. Clients that previously called `license(args: { spdxId: "..." })` must now also
    supply `assetId`. Existing calls without `assetId` will fail validation."""

    spdx_id: str = Field(alias="spdxId")
    asset_id: str = Field(alias="assetId")


class NotificationsInput(BaseModel):
    cursor: Optional["Cursor"] = None
    "Cursor for pagination. Use `first` to limit the number of notifications returned."
    filter: Optional["NotificationsFilter"] = None
    "Optional filter for notifications."
    sort: Optional["NotificationsSort"] = None
    "Optional sort configuration."


class NotificationsFilter(BaseModel):
    fields: Optional[list[Optional["NotificationsFieldFilter"]]] = None
    type: Optional["NotificationTypeFilter"] = None
    "Filter by notification type."
    parser: Optional["NotificationParserFilter"] = None
    "Filter by parser type."
    asset_id: Optional["StringFilter"] = Field(alias="assetId", default=None)
    "Filter by asset ID."
    created_at: Optional["DateTimeFilter"] = Field(alias="createdAt", default=None)
    "Filter by creation date."
    is_unread: Optional["BooleanFilter"] = Field(alias="isUnread", default=None)
    "Filter by unread status."


class NotificationsFieldFilter(BaseModel):
    field_name: Optional[NotificationField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class NotificationTypeFilter(BaseModel):
    eq: Optional[NotificationType] = None
    any: Optional[list[NotificationType]] = None


class NotificationParserFilter(BaseModel):
    eq: Optional[NotificationParser] = None
    any: Optional[list[NotificationParser]] = None


class NotificationsSort(BaseModel):
    field: Optional[NotificationSortField] = None
    order: Optional[SortOrder] = None


class UpdateNotificationSettingsInput(BaseModel):
    settings: "NotificationSettingsInput"
    update_mask: Optional[list[str]] = Field(alias="updateMask", default=None)


class NotificationSettingsInput(BaseModel):
    allow_user_overrides: Optional[bool] = Field(
        alias="allowUserOverrides", default=None
    )
    email_notifications_enabled: Optional[bool] = Field(
        alias="emailNotificationsEnabled", default=None
    )
    notification_timeframe: Optional[NotificationTimeframe] = Field(
        alias="notificationTimeframe", default=None
    )
    preferences: Optional[list["NotificationPreferenceInput"]] = None


class NotificationPreferenceInput(BaseModel):
    name: Optional[str] = None
    type: Optional[NotificationSettingsType] = None
    console: Optional[str] = None
    console_enabled: Optional[bool] = Field(alias="consoleEnabled", default=None)
    email: Optional[str] = None
    email_enabled: Optional[bool] = Field(alias="emailEnabled", default=None)
    webhook: Optional[str] = None
    webhook_enabled: Optional[bool] = Field(alias="webhookEnabled", default=None)
    controls: Optional[list[Optional["NotificationControlInput"]]] = None


class NotificationControlInput(BaseModel):
    vulnerability: Optional["VulnerabilityControlInput"] = None
    certificate_validity: Optional["CertificateControlInput"] = Field(
        alias="certificateValidity", default=None
    )
    asset_analysis: Optional["AssetAnalysisControlInput"] = Field(
        alias="assetAnalysis", default=None
    )
    sbom_findings: Optional["SbomFindingsControlInput"] = Field(
        alias="sbomFindings", default=None
    )
    user_management: Optional["UserManagementControlInput"] = Field(
        alias="userManagement", default=None
    )


class VulnerabilityControlInput(BaseModel):
    severities: Optional[list[VulnerabilitiesSeveritiesSelection]] = None
    exploits: Optional[list[VulnerabilitiesExploitsSelection]] = None


class CertificateControlInput(BaseModel):
    min_validity: Optional[CertificateValidityPeriod] = Field(
        alias="minValidity", default=None
    )
    max_validity: Optional[CertificateValidityPeriod] = Field(
        alias="maxValidity", default=None
    )


class AssetAnalysisControlInput(BaseModel):
    events: Optional[list[AssetAnalysisEventSelection]] = None


class SbomFindingsControlInput(BaseModel):
    findings: Optional[list[NewSBOMFindingsSelection]] = None


class UserManagementControlInput(BaseModel):
    events: Optional[list[UserManagementEventSelection]] = None


class ListNotificationConfigurationsInput(BaseModel):
    cursor: Optional["Cursor"] = None
    "Cursor for pagination. Use `first` to limit the number of configurations returned."
    filter: Optional["NotificationConfigurationsFilter"] = None
    sort: Optional["NotificationConfigurationsSort"] = None


class ListNotificationLogsInput(BaseModel):
    """Input for listing notification logs."""

    cursor: Optional["Cursor"] = None
    "Cursor for pagination."
    filter: Optional["NotificationLogsFilter"] = None
    sort: Optional["NotificationLogsSort"] = None


class NotificationConfigurationsFilter(BaseModel):
    fields: Optional[list[Optional["NotificationConfigurationsFilterField"]]] = None


class NotificationConfigurationsFilterField(BaseModel):
    field_name: Optional[NotificationConfigurationsField] = Field(
        alias="fieldName", default=None
    )
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class NotificationConfigurationsSort(BaseModel):
    field: Optional[NotificationConfigurationsField] = None
    order: Optional[SortOrder] = None


class NotificationLogsFilter(BaseModel):
    fields: Optional[list[Optional["NotificationLogsFilterField"]]] = None


class NotificationLogsFilterField(BaseModel):
    field_name: Optional[NotificationLogsField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class NotificationLogsSort(BaseModel):
    field: Optional[NotificationLogsField] = None
    order: Optional[SortOrder] = None


class CreateNotificationConfigurationInput(BaseModel):
    """Payload for creating a notification configuration."""

    configuration: "NotificationConfigurationCreateInput"


class UpdateNotificationConfigurationInput(BaseModel):
    """Payload for updating a notification configuration. Id is required; other fields are optional (only sent fields are updated)."""

    configuration: "NotificationConfigurationUpdateInput"


class DeleteNotificationConfigurationInput(BaseModel):
    """Payload for deleting a notification configuration."""

    id: str


class NotifyNotificationConfigurationInput(BaseModel):
    """Input for triggering notification delivery for a configuration."""

    id: str


class NotificationConfigurationCreateInput(BaseModel):
    """Input for creating a notification configuration. Id is not set by the client."""

    name: Optional[str] = None
    disabled: Optional[bool] = None
    silenced: Optional[bool] = None
    type: NotificationConfigurationType
    channel: NotificationConfigurationChannel
    inventory_scopes: Optional[list["NotificationInventoryScopeInput"]] = Field(
        alias="inventoryScopes", default=None
    )
    activity_scopes: list["NotificationActivityScopeInput"] = Field(
        alias="activityScopes"
    )
    channel_configuration: Optional["NotificationChannelConfigurationInput"] = Field(
        alias="channelConfiguration", default=None
    )
    "Channel-specific settings. Exactly one of webhook, email, or application must be set, consistent with `channel`."


class NotificationConfigurationUpdateInput(BaseModel):
    """Input for updating a notification configuration. Id is required; other fields are optional."""

    id: str
    name: str
    disabled: bool
    silenced: bool
    type: NotificationConfigurationType
    channel: NotificationConfigurationChannel
    inventory_scopes: Optional[list["NotificationInventoryScopeInput"]] = Field(
        alias="inventoryScopes", default=None
    )
    activity_scopes: list["NotificationActivityScopeInput"] = Field(
        alias="activityScopes"
    )
    channel_configuration: "NotificationChannelConfigurationInput" = Field(
        alias="channelConfiguration"
    )
    "Channel-specific settings. Exactly one of webhook, email, or application must be set, consistent with `channel`."


class NotificationChannelConfigurationInput(BaseModel):
    """Exactly one of webhook, email, or application must be set."""

    webhook: Optional["NotificationConfigurationWebhookInput"] = None
    email: Optional["NotificationConfigurationEmailInput"] = None
    application: Optional["NotificationConfigurationApplicationInput"] = None


class NotificationInventoryScopeInput(BaseModel):
    organization: Optional[bool] = None
    group_id: Optional[str] = Field(alias="groupId", default=None)
    asset_id: Optional[str] = Field(alias="assetId", default=None)


class NotificationActivityScopeInput(BaseModel):
    activity_type: Optional[NotificationActivityKind] = Field(
        alias="activityType", default=None
    )
    entity_type: Optional[ActivityEntityType] = Field(alias="entityType", default=None)
    threshold: Optional["NotificationActivityThresholdInput"] = None


class NotificationActivityThresholdInput(BaseModel):
    key: NotificationActivityThresholdField
    value: str
    operator: NotificationActivityThresholdOperator


class NotificationConfigurationWebhookInput(BaseModel):
    url: str


class NotificationConfigurationEmailInput(BaseModel):
    address: str


class NotificationConfigurationApplicationInput(BaseModel):
    """Application channel has no extra fields, but we keep an explicit input for future extensibility."""

    empty: Optional[bool] = Field(alias="_empty", default=None)


class OrgLevelInformationInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class CursorV3(BaseModel):
    first: int
    after: Optional[str] = None
    before: Optional[str] = None


class Cursor(BaseModel):
    first: Optional[int] = None
    after: Optional[str] = None
    last: Optional[int] = None
    before: Optional[str] = None


class PrivateKeysInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional["ListPrivateKeysFilter"] = None
    sort: Optional["ListPrivateKeysSort"] = None


class ListPrivateKeysFilter(BaseModel):
    fields: Optional[list[Optional["ListPrivateKeysFilterField"]]] = None
    algorithm_type: Optional["StringFilter"] = Field(
        alias="algorithmType", default=None
    )


class ListPrivateKeysFilterField(BaseModel):
    field_name: Optional[PrivateKeysField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class ListPrivateKeysSort(BaseModel):
    field: Optional[PrivateKeysField] = None
    order: Optional[SortOrder] = None


class PrivateKeyExternalFiltersInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class PrivateKeyIdentifierInput(BaseModel):
    file_path: str = Field(alias="filePath")
    match_hash: str = Field(alias="matchHash")


class RemediatePrivateKeysInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    private_keys: list["PrivateKeyIdentifierInput"] = Field(alias="privateKeys")
    status: CryptoRemediationStatus
    details: Optional[str] = None


class PublicKeysInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional["ListPublicKeysFilter"] = None
    sort: Optional["ListPublicKeysSort"] = None


class ListPublicKeysFilter(BaseModel):
    fields: Optional[list[Optional["ListPublicKeysFilterField"]]] = None
    algorithm_type: Optional["StringFilter"] = Field(
        alias="algorithmType", default=None
    )


class ListPublicKeysFilterField(BaseModel):
    field_name: Optional[PublicKeysField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class ListPublicKeysSort(BaseModel):
    field: Optional[PublicKeysField] = None
    order: Optional[SortOrder] = None


class PublicKeyExternalFiltersInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class PublicKeyIdentifierInput(BaseModel):
    file_path: str = Field(alias="filePath")
    match_hash: str = Field(alias="matchHash")


class RemediatePublicKeysInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    public_keys: list["PublicKeyIdentifierInput"] = Field(alias="publicKeys")
    status: CryptoRemediationStatus
    details: Optional[str] = None


class CreateAssetComparisonReportInput(BaseModel):
    asset_a: str = Field(alias="assetA")
    asset_b: str = Field(alias="assetB")


class GetAssetComparisonReportInput(BaseModel):
    report_id: str = Field(alias="reportId")


class ListAssetComparisonReportsInput(BaseModel):
    cursor: Optional["Cursor"] = None
    filter: Optional["ListAssetComparisonReportsFilterInput"] = None
    sort: Optional["ListAssetComparisonReportsSortInput"] = None


class ListAssetComparisonReportsFilterInput(BaseModel):
    search: Optional[str] = None
    type: Optional[str] = None


class ListAssetComparisonReportsSortInput(BaseModel):
    field: Optional[str] = None
    order: Optional[SortOrder] = None


class DeleteAssetComparisonReportInput(BaseModel):
    report_id: str = Field(alias="reportId")


class RiseAIAnalysisDataInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class SearchInput(BaseModel):
    query: str
    artifacts: list[ArtifactName]
    asset_ids: Optional[list[str]] = Field(alias="assetIds", default=None)
    group_ids: Optional[list[str]] = Field(alias="groupIds", default=None)
    cursor: Optional["Cursor"] = None


class SecretsFilter(BaseModel):
    """Filter for secrets."""

    type: Optional[list[Optional[SecretType]]] = None
    severity: Optional[list[Optional[SecretSeverity]]] = None
    category: Optional[SecretCategory] = None
    search: Optional[str] = None
    status: Optional[list[Optional[SecretRemediationStatus]]] = None
    is_reachable: Optional[bool] = Field(alias="isReachable", default=None)
    "When true, only secrets marked as reachable (reachability v2).\nPushed to gRPC for list queries; categories-summary rebuilds from filtered list."


class SecretInput(BaseModel):
    """Input for querying a single secret."""

    id: str
    "Unique secret identifier."
    reveal_secret: Optional[bool] = Field(alias="revealSecret", default=False)
    "If true, attempts to return the raw secret value."


class SecretsInput(BaseModel):
    """Input for listing secrets on an asset."""

    asset_id: str = Field(alias="assetId")
    "Asset identifier whose secrets are being listed.\nMaps to ListAssetSecretsRequest.asset_id."
    cursor: "Cursor"
    "Pagination configuration."
    filter: Optional["SecretsFilter"] = None
    "Optional structured filter for secrets."
    sort: Optional["SecretsSort"] = None
    "Optional order by expression."


class SecretsSort(BaseModel):
    field: Optional[SecretsField] = None
    order: Optional[SortOrder] = None


class SecretCategoriesInput(BaseModel):
    """Input for listing secret categories on an asset."""

    asset_id: str = Field(alias="assetId")
    "Asset identifier whose secrets are being listed.\nMaps to ListAssetSecretsRequest.asset_id."
    filter: Optional["SecretsFilter"] = None
    "Optional structured filter for secrets."


class SecretsSummaryInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class SecretTypesAndCountInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class SecretStatusCountInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class CreateSecretsRemediationInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    secret_ids: list[str] = Field(alias="secretIds")
    status: SecretRemediationStatus
    description: Optional[str] = None


class SiftInput(BaseModel):
    asset_ids: Optional[list[str]] = Field(alias="assetIds", default=None)
    search_type: SiftSearchType = Field(alias="searchType")
    text: str
    threshold: float


class VulnerabilitiesFunnelChartInput(BaseModel):
    asset_id: Optional[str] = Field(alias="assetId", default=None)
    group_ids: Optional[list[Optional[str]]] = Field(alias="groupIds", default=None)
    is_reachable: Optional[bool] = Field(alias="isReachable", default=None)


class AnalyticsOrgInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class AnalyticsAssetHighlightedProductsInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    is_reachable: Optional[bool] = Field(alias="isReachable", default=None)


class AnalyticsAssetInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")


class HighProfileExploitInput(BaseModel):
    cursor: "Cursor"
    filter: Optional["HighProfileExploitFilter"] = None
    sort: Optional["HighProfileExploitSort"] = None
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class HighProfileExploitFilter(BaseModel):
    fields: Optional[list[Optional["HighProfileExploitFieldFilter"]]] = None


class HighProfileExploitFieldFilter(BaseModel):
    field_name: HighProfileExploitFilterField = Field(alias="fieldName")
    value: list[str]
    operation: FieldFilterOperation


class HighProfileExploitSort(BaseModel):
    field: Optional[HighProfileExploitSortField] = None
    order: Optional[SortOrder] = None


class ActivityInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: Optional["Cursor"] = None


class FilesInput(BaseModel):
    cursor: Optional["CursorV3"] = None
    filter: Optional["ListFilesFilter"] = None
    sort: Optional["ListFilesSort"] = None


class FilesystemsInput(BaseModel):
    filesystem_id: Optional[str] = Field(alias="filesystemId", default=None)


class ListFilesSort(BaseModel):
    field: Optional[ListFilesSortField] = None
    order: Optional[SortOrder] = None


class ListFilesFilter(BaseModel):
    fields: Optional[list[Optional["ListFilesFilterField"]]] = None
    hide_failed: Optional[bool] = Field(alias="hideFailed", default=None)
    search: Optional["SimilaritySearchInput"] = None
    selected_severity_filters: Optional[list[Optional[RiskCategoryFilter]]] = Field(
        alias="selectedSeverityFilters", default=None
    )


class ListFilesFilterField(BaseModel):
    field_name: Optional[ListFilesFilterFieldEnum] = Field(
        alias="fieldName", default=None
    )
    value: list[str]
    operation: Optional[FieldFilterOperation] = None


class SimilaritySearchInput(BaseModel):
    text: str
    threshold: float


class AssetsRelayInput(BaseModel):
    cursor: "Cursor"
    filter: Optional["AssetsFilter"] = None
    sort: Optional["AssetsSort"] = None


class AssetsFilter(BaseModel):
    fields: Optional[list[Optional["AssetsFieldFilter"]]] = None
    hide_failed: Optional[bool] = Field(alias="hideFailed", default=None)
    selected_severity_filters: Optional[list[Optional[RiskCategoryFilter]]] = Field(
        alias="selectedSeverityFilters", default=None
    )


class AssetsFieldFilter(BaseModel):
    field_name: AssetsFilterField = Field(alias="fieldName")
    value: list[Any]
    operation: FieldFilterOperation


class AssetsSort(BaseModel):
    field: Optional[AssetsSortField] = None
    order: Optional[SortOrder] = None


class AssetOverviewInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)
    filter: Optional["AssetOverviewFilter"] = None
    sort: Optional["AssetOverviewSort"] = None
    cursor: "Cursor"


class AssetOverviewFilter(BaseModel):
    vulnerability_id: Optional[str] = Field(alias="vulnerabilityId", default=None)
    in_the_wild: Optional[bool] = Field(alias="inTheWild", default=None)
    exploit_found: Optional[bool] = Field(alias="exploitFound", default=None)
    risk_score_category: Optional[AssetOverviewRiskCategory] = Field(
        alias="riskScoreCategory", default=None
    )
    in_known_exploited_vulnerabilities: Optional[bool] = Field(
        alias="inKnownExploitedVulnerabilities", default=None
    )
    high_profile_vulnerabilities: Optional["HighProfileExploitCategoryFilter"] = Field(
        alias="highProfileVulnerabilities", default=None
    )


class HighProfileExploitCategoryFilter(BaseModel):
    category: Optional[HighProfileCategory] = None
    name: Optional[str] = None


class AssetOverviewSort(BaseModel):
    field: Optional[AssetOverviewSortField] = None
    order: Optional[SortOrder] = None


class AssetsInput(BaseModel):
    cursor: Optional["CursorV3"] = None
    filter: Optional["ListComponentFilter"] = None
    sort: Optional["ListComponentSort"] = None


class AssetInput(BaseModel):
    asset_id: Optional[str] = Field(alias="assetId", default=None)


class AssetStatusInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class AssetUploadInput(BaseModel):
    upload_id: Optional[str] = Field(alias="uploadId", default=None)


class FileDownloadInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    filesystem_id: Optional[str] = Field(alias="filesystemId", default=None)
    file_id: Optional[str] = Field(alias="fileId", default=None)
    file_paths: list[str] = Field(alias="filePaths")


class FileListDownloadInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class ExtractedFirmwareDownloadInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    filesystem_id: Optional[str] = Field(alias="filesystemId", default=None)


class FirmwareDownloadInput(BaseModel):
    asset_id: str = Field(alias="assetId")


class ListComponentFilter(BaseModel):
    fields: Optional[list[Optional["ListComponentFilterField"]]] = None
    hide_failed: Optional[bool] = Field(alias="hideFailed", default=None)
    selected_severity_filters: Optional[list[Optional[RiskCategoryFilter]]] = Field(
        alias="selectedSeverityFilters", default=None
    )


class ListComponentFilterField(BaseModel):
    field_name: Optional[ListComponentFilterFieldEnum] = Field(
        alias="fieldName", default=None
    )
    value: list[str]
    operation: Optional[FieldFilterOperation] = None


class ListComponentSort(BaseModel):
    field: Optional[ListComponentSortField] = None
    order: Optional[SortOrder] = None


class IdentificationInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    identification_ids: list[str] = Field(alias="identificationIds")


class DependencyDetailsInput(BaseModel):
    """Dependency details of the component to be added."""

    name: str
    "Component's name"
    type: ComponentType
    "Type of the component (e.g., library, application)"
    vendor: Optional[str] = None
    "Component's vendor"
    version: Optional[str] = None
    "Component's version"
    description: Optional[str] = None
    "Optional description of the component"
    purls: Optional[list[Optional[str]]] = None
    "List of associated Package URLs (PURLs)"
    cpes: Optional[list[Optional[str]]] = None
    "List of associated CPE identifiers"
    license: Optional[list[Optional[str]]] = None
    "List of associated licenses"


class AddDependencyInput(BaseModel):
    """Request input for adding an dependency to an asset."""

    composed_asset_id: str = Field(alias="composedAssetId")
    "ID of the target asset"
    reason: Optional[str] = None
    "Reason for adding this dependency"
    dependency_fields: "DependencyDetailsInput" = Field(alias="dependencyFields")
    "Dependency details"


class ModifyDependencyInput(BaseModel):
    """Request input for editing an existing dependency."""

    identification: "IdentificationInput"
    "Targeting existing dependency via composedAssetId + identificationIds"
    dependency_fields: "DependencyDetailsInput" = Field(alias="dependencyFields")
    "New dependency data to replace the existing one"
    reason: Optional[str] = None
    "Optional new reason for the edit"


class UpdateAssetInput(BaseModel):
    id: str
    vendor: Optional[str] = None
    "Component's vendor / vendor"
    name: Optional[str] = None
    "Component's name"
    version: Optional[str] = None
    "Component's version"
    product: Optional[str] = None
    "Component's model/product"


class SubmitAssetInput(BaseModel):
    name: Optional[str] = None
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    version: Optional[str] = None
    asset_cpe: Optional[str] = Field(alias="assetCpe", default=None)
    architecture: Optional[str] = None
    kernel_version: Optional[str] = Field(alias="kernelVersion", default=None)
    os: Optional[str] = None
    bitness: Optional[int] = None
    family: Optional[str] = None
    type: Optional[AssetType] = None
    sbom_type: Optional[SbomType] = Field(alias="sbomType", default=None)
    "sbomType = Whether is SBOM ingestion or FIRMWARE ingestion. value means SBOM ingestion //  CycloneDX, SPDX"
    cyclonedx_version: Optional[CycloneDxVersion] = Field(
        alias="cyclonedxVersion", default=None
    )
    "SBOM spec version for CycloneDX ingest (v1.1–v1.7). Prefer over sbomVersion."
    spdx_version: Optional[SpdxVersion] = Field(alias="spdxVersion", default=None)
    "SBOM spec version for SPDX ingest (v2.1–v2.3, v3.0, v3.0.1). Prefer over sbomVersion."
    sbom_format: Optional[SbomFormat] = Field(alias="sbomFormat", default=None)
    "format: JSON, XML, SPDX"
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)
    license: Optional[str] = None


class AssetsByStatusInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class AssetsCountInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class FilesCountInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class VulnerabilitiesCountInput(BaseModel):
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class AssetGroupMembersInput(BaseModel):
    group_id: str = Field(alias="groupId")
    cursor: "Cursor"
    sort: Optional["AssetsSort"] = None


class AssetGroupAnalyticsInput(BaseModel):
    group_id: str = Field(alias="groupId")


class RemoveAllAssetGroupsFromAssetsInput(BaseModel):
    asset_ids: list[str] = Field(alias="assetIds")


class AddAssetGroupsToAssetsInput(BaseModel):
    asset_ids: list[str] = Field(alias="assetIds")
    group_ids: Optional[list[str]] = Field(alias="groupIds", default=None)


class SetAssetsToAssetGroupInput(BaseModel):
    group_id: str = Field(alias="groupId")
    asset_ids: Optional[list[str]] = Field(alias="assetIds", default=None)


class SetAssetGroupsToAssetInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    group_ids: Optional[list[str]] = Field(alias="groupIds", default=None)


class AssetGroupsInput(BaseModel):
    cursor: "Cursor"
    filter: Optional[str] = None
    sort: Optional["AssetGroupsSort"] = None


class AssetGroupsSort(BaseModel):
    field: Optional[AssetGroupsField] = None
    order: Optional[SortOrder] = None


class CreateAssetGroupInput(BaseModel):
    name: str
    description: Optional[str] = None
    asset_ids: Optional[list[str]] = Field(alias="assetIds", default=None)


class UpdateAssetGroupInput(BaseModel):
    id: str
    name: str
    description: Optional[str] = None


class DeleteAssetGroupInput(BaseModel):
    id: str


class AddAssetsToAssetGroupInput(BaseModel):
    id: str
    asset_ids: list[str] = Field(alias="assetIds")


class RemoveAssetsFromAssetGroupInput(BaseModel):
    id: str
    asset_ids: list[str] = Field(alias="assetIds")


class BinaryProtectionsSummaryInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")


class GetCertificateReachabilityInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    file_path: str = Field(alias="filePath")
    sha_256: str = Field(alias="sha256")


class packageDependenciesByIdInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    identification_ids: Optional[list[str]] = Field(
        alias="identificationIds", default=None
    )


class GroupedDependenciesInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    filter: Optional["GroupedDependencyFilter"] = None
    sort: Optional["GroupedDependencySort"] = None
    cursor: Optional["Cursor"] = None
    grouped_by: Optional[DependencyGroupByField] = Field(
        alias="groupedBy", default=None
    )
    "Regular dependency input up to here"


class DependencyKnownExploitsInput(BaseModel):
    identification_ids: list[str] = Field(alias="identificationIds")
    "This is the identification's id list of the dependency"
    composed_asset_id: str = Field(alias="composedAssetId")
    "This is the composedAssetId"


class DependencyInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    filter: Optional["DependencyFilter"] = None
    sort: Optional["DependencySort"] = None
    cursor: Optional["Cursor"] = None


class DependencyFilter(BaseModel):
    analytic_filter: Optional["DependencyAnalyticFilter"] = Field(
        alias="analyticFilter", default=None
    )
    "Filter by vulnerability fields"
    fields: Optional[list[Optional["DependencyFieldFilter"]]] = None
    package_match: Optional["ValueFilter"] = Field(alias="packageMatch", default=None)
    is_reachable: Optional[bool] = Field(alias="isReachable", default=None)
    "When true, only dependencies marked as reachable (reachability v2)."


class DependencyAnalyticFilter(BaseModel):
    vulnerability: Optional["ValueFilter"] = None
    exploit: Optional["ValueFilter"] = None


class DependencySort(BaseModel):
    field: Optional[DependencySortField] = None
    order: Optional[SortOrder] = None


class GroupedDependencySort(BaseModel):
    field: Optional[GroupedDependencySortField] = None
    order: Optional[SortOrder] = None


class GroupedDependencyFilter(BaseModel):
    fields: Optional[list[Optional["GroupedDependencyFieldFilter"]]] = None
    "Filter by grouped dependency fields"
    analytic_filter: Optional["DependencyAnalyticFilter"] = Field(
        alias="analyticFilter", default=None
    )
    "Filter by vulnerability fields"


class DependencyFieldFilter(BaseModel):
    field_name: Optional[DependencyField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class GroupedDependencyFieldFilter(BaseModel):
    field_name: GroupedDependencyField = Field(alias="fieldName")
    value: Any
    operation: FilterFieldOperation


class ListAiProvidersInput(BaseModel):
    composed_asset_id: Optional[str] = Field(alias="composedAssetId", default=None)


class GetAiModelDataInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    component_id: str = Field(alias="componentId")


class ValueFilter(BaseModel):
    any: Optional[list[str]] = None
    all: Optional[list[str]] = None
    has: Optional["BooleanFilter"] = None


class GetDependencyReachabilityInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    component_id: str = Field(alias="componentId")


class VulnerabilityJiraTicketsInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    advisory_id: str = Field(alias="advisoryId")
    identification_ids: Optional[list[str]] = Field(
        alias="identificationIds", default=None
    )


class JiraIntegrationUnlinkVulnerabilityTicketInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    advisory_id: str = Field(alias="advisoryId")
    identification_ids: Optional[list[str]] = Field(
        alias="identificationIds", default=None
    )
    ticket_id: str = Field(alias="ticketId")


class JiraIntegrationDeleteConnectedSpaceInput(BaseModel):
    space_id: str = Field(alias="spaceId")


class JiraIntegrationAddConnectedSpaceInput(BaseModel):
    space_id: Optional[str] = Field(alias="spaceId", default=None)


class JiraIntegrationSetupActionInput(BaseModel):
    action: JiraSetupAction
    site_id: Optional[str] = Field(alias="siteId", default=None)
    space_ids: Optional[list[str]] = Field(alias="spaceIds", default=None)


class JiraIntegrationSetupInput(BaseModel):
    mode: Optional[JiraSetupMode] = None
    initialize: Optional[bool] = None


class MisconfigurationsInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: "Cursor"
    filter: Optional["MisconfigurationsFilter"] = None
    sort: Optional["MisconfigurationsSort"] = None


class MisconfigurationsFilter(BaseModel):
    fields: Optional[list[Optional["MisconfigurationsFilterField"]]] = None


class MisconfigurationsFilterField(BaseModel):
    field_name: Optional[MisconfigurationsField] = Field(
        alias="fieldName", default=None
    )
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class MisconfigurationsSort(BaseModel):
    field: Optional[MisconfigurationsField] = None
    order: Optional[SortOrder] = None


class AddSecurityGroupMemberInput(BaseModel):
    """Input payload for the `addSecurityGroupMember` mutation. Adds a user as a member
    of the targeted security group via the RBAC service."""

    security_group_id: str = Field(alias="securityGroupId")
    "The id of the security group to add the user to."
    user_id: str = Field(alias="userId")
    "The id of the user to add as a member of the security group."


class RemoveSecurityGroupMemberInput(BaseModel):
    """Input payload for the `removeSecurityGroupMember` mutation. Removes a user from
    the targeted security group via the RBAC service."""

    security_group_id: str = Field(alias="securityGroupId")
    "The id of the security group to remove the user from."
    user_id: str = Field(alias="userId")
    "The id of the user to remove from the security group."


class CreateSecurityGroupInput(BaseModel):
    """Input payload for the `createSecurityGroup` mutation. Creates a security group
    in the current organization via the RBAC service."""

    name: str
    "Display name for the new security group."
    description: Optional[str] = None
    "Optional description shown in the Users & Access UI."
    member_emails: Optional[list[str]] = Field(alias="memberEmails", default=None)
    "Org user emails to add as direct members when the group is created.\nEach email must match an existing org user; unknown emails fail the request."


class UpdateSecurityGroupInput(BaseModel):
    """Input payload for the `updateSecurityGroup` mutation. Updates name and/or description
    for an existing security group via the RBAC service."""

    security_group_id: str = Field(alias="securityGroupId")
    "The id of the security group to update."
    name: str
    "New display name for the security group."
    description: Optional[str] = None
    "Optional description. Omit or pass empty string to clear."
    member_emails: Optional[list[str]] = Field(alias="memberEmails", default=None)
    "When provided, replaces the group's direct member set with these org user emails.\nAn empty list clears direct members. Omit to leave membership unchanged."


class DeleteSecurityGroupInput(BaseModel):
    """Input payload for the `deleteSecurityGroup` mutation. Deletes a security group
    via the RBAC service."""

    security_group_id: str = Field(alias="securityGroupId")
    "The id of the security group to delete."


class InviteOrgUserInput(BaseModel):
    """Input payload for the `inviteUser` mutation. Invites a user to the current organization
    through the RBAC service."""

    email: str
    "The email address of the user to invite."
    display_name: Optional[str] = Field(alias="displayName", default=None)
    "Optional display name for the invited user."
    security_group_ids: Optional[list[str]] = Field(
        alias="securityGroupIds", default=None
    )
    "Optional list of security group IDs to add the invited user to upon creation."
    role_id: Optional[str] = Field(alias="roleId", default=None)
    "Optional role to grant the invited user directly at the organization level.\nWhen set, the RBAC service creates an organization-scoped ACR granting this\nrole to the new user, independent of any security group membership."


class CreateCustomRoleInput(BaseModel):
    """Input payload for the `createCustomRole` mutation. Creates an org-scoped
    custom RBAC role via the RBAC service."""

    name: str
    "Display name for the new custom role."
    description: Optional[str] = None
    "Optional description shown in the Users & Access UI."
    permissions: list[str]
    "Permission identifiers that should be granted to this role."


class UpdateCustomRoleInput(BaseModel):
    """Input payload for the `updateCustomRole` mutation. Updates an existing custom
    role via the RBAC service."""

    role_id: str = Field(alias="roleId")
    "The id of the custom role to update."
    name: str
    "New display name for the custom role."
    description: Optional[str] = None
    "Optional description. Omit or pass empty string to clear."
    permissions: list[str]
    "Permission identifiers that should be granted to this role."


class DeleteCustomRoleInput(BaseModel):
    """Input payload for the `deleteCustomRole` mutation. Deletes a custom role
    via the RBAC service."""

    role_id: str = Field(alias="roleId")
    "The id of the custom role to delete."


class AcrBindingInput(BaseModel):
    """Shared binding fields for create and replace ACR mutations.
    Exactly one of `roleId` or `directPermissionIds` must be provided."""

    entity_type: AcrEntityType = Field(alias="entityType")
    entity_id: str = Field(alias="entityId")
    role_id: Optional[str] = Field(alias="roleId", default=None)
    "Role to grant. Omit or pass empty string for direct-permission ACRs."
    resource_type: AcrResourceType = Field(alias="resourceType")
    resource_id: Optional[str] = Field(alias="resourceId", default=None)
    "Resource identifier. Omit for organization-level grants when not applicable."
    expires_at: Optional[str] = Field(alias="expiresAt", default=None)
    "Optional ISO-8601 expiration time. Omit for non-expiring grants."
    direct_permission_ids: Optional[list[str]] = Field(
        alias="directPermissionIds", default=None
    )
    "Permission identifiers for role-less (direct-permission) ACRs."


class CreateAcrInput(BaseModel):
    """Input payload for the `createACR` mutation."""

    binding: "AcrBindingInput"


class DeleteAcrInput(BaseModel):
    """Input payload for the `deleteACR` mutation."""

    acr_id: str = Field(alias="acrId")


class BulkDeleteAcrsInput(BaseModel):
    """Input payload for the `bulkDeleteACRs` mutation."""

    acr_ids: list[str] = Field(alias="acrIds")


class ReplaceAcrInput(BaseModel):
    """Input payload for the `replaceACR` mutation."""

    acr_id: str = Field(alias="acrId")
    binding: "AcrBindingInput"


class SetOrgUserStatusInput(BaseModel):
    """Input payload for the `setOrgUserStatus` mutation. Enables or disables a user
    in the current organization through the RBAC service."""

    user_id: str = Field(alias="userId")
    "The id of the user whose status should be updated."
    status: OrgUserStatus
    "The new status to apply to the user."


class RemoveOrgUserInput(BaseModel):
    """Input payload for the `removeOrgUser` mutation. Permanently removes a user from
    the current organization through the RBAC service."""

    user_id: str = Field(alias="userId")
    "The id of the user to remove from the current organization."


class GetSecretReachabilityInput(BaseModel):
    composed_asset_id: str = Field(alias="composedAssetId")
    secret_id: str = Field(alias="secretId")


class UsersInput(BaseModel):
    cursor: "Cursor"


class SetUserRoleInput(BaseModel):
    next_role: str = Field(alias="nextRole")
    user_id: str = Field(alias="userId")


class UserActionInput(BaseModel):
    type: UserActionEnum
    user_id: str = Field(alias="userId")


class UserInput(BaseModel):
    id: str


class InviteUserInput(BaseModel):
    email: str
    role: str


class UpdateUserInput(BaseModel):
    user_id: str = Field(alias="userId")
    name: Optional[str] = None
    confirm: Optional[str] = None
    password: Optional[str] = None


class GetVulnReachabilityInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    advisory_id: str = Field(alias="advisoryId")
    identification_ids: list[str] = Field(alias="identificationIds")


class CreateAssetVulnerabilityRemediationInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    remediation_id: "RemediationId" = Field(alias="remediationId")
    justification: Optional[VexJustification] = None
    responses: Optional[list[Optional[RemediationResponses]]] = None
    description: Optional[str] = None
    status: VexStatus


class CreateAssetVulnerabilityRemediationsInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    remediation_ids: list["RemediationId"] = Field(alias="remediationIds")
    justification: Optional[VexJustification] = None
    responses: Optional[list[Optional[RemediationResponses]]] = None
    description: Optional[str] = None
    status: VexStatus


class RemediationId(BaseModel):
    vulnerability_id: str = Field(alias="vulnerabilityId")
    identification_ids: Optional[list[str]] = Field(
        alias="identificationIds", default=None
    )


class AssetVulnerabilityRemediationInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    remediation_id: str = Field(alias="remediationId")
    vulnerability_id: str = Field(alias="vulnerabilityId")


class CreateAllAssetVulnerabilitiesRemediationInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    vulnerability_filter: "VulnerabilityFilter" = Field(alias="vulnerabilityFilter")
    justification: Optional[VexJustification] = None
    responses: Optional[list[Optional[RemediationResponses]]] = None
    description: Optional[str] = None
    status: VexStatus


class VulnerabilityOverviewInput(BaseModel):
    filter: Optional["VulnerabilityOverviewFilter"] = None
    sort: Optional["VulnerabilityOverviewSort"] = None
    cursor: "Cursor"
    asset_group_ids: Optional[list[str]] = Field(alias="assetGroupIds", default=None)


class VulnerabilityOverviewFilter(BaseModel):
    in_the_wild: Optional[bool] = Field(alias="inTheWild", default=None)
    in_ransomware: Optional[bool] = Field(alias="inRansomware", default=None)
    in_threat_actors: Optional[bool] = Field(alias="inThreatActors", default=None)
    in_botnets: Optional[bool] = Field(alias="inBotnets", default=None)
    exploit_found: Optional[bool] = Field(alias="exploitFound", default=None)
    in_known_exploited_vulnerabilities: Optional[bool] = Field(
        alias="inKnownExploitedVulnerabilities", default=None
    )
    vulnerability_is_reachable: Optional[bool] = Field(
        alias="vulnerabilityIsReachable", default=None
    )
    kev_due_datetime: Optional["DateTimeFilter"] = Field(
        alias="kevDueDatetime", default=None
    )
    created_datetime: Optional["DateTimeFilter"] = Field(
        alias="createdDatetime", default=None
    )
    attacks: Optional["HighProfileExploitCategoryFilter"] = None
    vulnerability_id: Optional[str] = Field(alias="vulnerabilityId", default=None)
    priority_score_str: Optional[str] = Field(alias="priorityScoreStr", default=None)
    severity: Optional[Severity] = None
    fields: Optional[list[Optional["VulnerabilityOverviewFieldFilter"]]] = None


class VulnerabilityOverviewSort(BaseModel):
    field: Optional[VulnerabilityOverviewSortField] = None
    order: Optional[SortOrder] = None


class VulnerabilityOverviewFieldFilter(BaseModel):
    field_name: VulnerabilityOverviewFilterField = Field(alias="fieldName")
    value: Any
    operation: FieldFilterOperation


class MatchVulnerabilitiesInput(BaseModel):
    """Vulnerability"""

    identifier: str


class VulnerabilityInput(BaseModel):
    id: str
    "Unique identifier for the vulnerability, e.g. cve-id"


class PaginatedVulnerabilitiesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: Optional["Cursor"] = None
    filter: Optional["VulnerabilityFilter"] = None
    sort: Optional["VulnerabilitySort"] = None


class PaginatedDetailedVulnerabilitiesInput(BaseModel):
    asset_id: str = Field(alias="assetId")
    cursor: Optional["Cursor"] = None
    filter: Optional["DetailedVulnerabilityFilter"] = None


class DetailedVulnerabilityFilter(BaseModel):
    created_datetime: Optional["DateTimeFilter"] = Field(
        alias="createdDatetime", default=None
    )
    updated_datetime: Optional["DateTimeFilter"] = Field(
        alias="updatedDatetime", default=None
    )


class VulnerabilityFilter(BaseModel):
    fields: Optional[list[Optional["VulnerabilityFieldFilter"]]] = None
    vulnerability: Optional["StringFilter"] = None
    in_botnets: Optional["BooleanFilter"] = Field(alias="inBotnets", default=None)
    in_threat_actors: Optional["BooleanFilter"] = Field(
        alias="inThreatActors", default=None
    )
    in_ransomware: Optional["BooleanFilter"] = Field(alias="inRansomware", default=None)
    in_known_attacks: Optional["BooleanFilter"] = Field(
        alias="inKnownAttacks", default=None
    )
    exploits: Optional["BooleanFilter"] = None
    in_known_exploited_vulnerabilities: Optional["BooleanFilter"] = Field(
        alias="inKnownExploitedVulnerabilities", default=None
    )
    has_fix_version: Optional["BooleanFilter"] = Field(
        alias="hasFixVersion", default=None
    )
    is_reachable: Optional["BooleanFilter"] = Field(alias="isReachable", default=None)
    kev_due_datetime: Optional["DateTimeFilter"] = Field(
        alias="kevDueDatetime", default=None
    )


class VulnerabilityFieldFilter(BaseModel):
    field_name: Optional[VulnerabilityField] = Field(alias="fieldName", default=None)
    value: Optional[Any] = None
    operation: Optional[FilterFieldOperation] = None


class VulnerabilitySort(BaseModel):
    field: Optional[VulnerabilitySortField] = None
    order: Optional[SortOrder] = None


class VulnerabilityExternalFiltersInput(BaseModel):
    asset_id: str = Field(alias="assetId")


ListAssetCorrelationsInput.model_rebuild()
BinaryProtectionsInput.model_rebuild()
BinaryProtectionsFilter.model_rebuild()
CertificatesInput.model_rebuild()
ListCertificatesFilter.model_rebuild()
RemediateCertificatesInput.model_rebuild()
HashesInput.model_rebuild()
HashesFilter.model_rebuild()
CredentialsInput.model_rebuild()
CredentialsFilter.model_rebuild()
ListAssetCryptoLibrariesInput.model_rebuild()
LicenseIssuesFilter.model_rebuild()
LicenseIssuesInput.model_rebuild()
NotificationsInput.model_rebuild()
NotificationsFilter.model_rebuild()
UpdateNotificationSettingsInput.model_rebuild()
NotificationSettingsInput.model_rebuild()
NotificationPreferenceInput.model_rebuild()
NotificationControlInput.model_rebuild()
ListNotificationConfigurationsInput.model_rebuild()
ListNotificationLogsInput.model_rebuild()
NotificationConfigurationsFilter.model_rebuild()
NotificationLogsFilter.model_rebuild()
CreateNotificationConfigurationInput.model_rebuild()
UpdateNotificationConfigurationInput.model_rebuild()
NotificationConfigurationCreateInput.model_rebuild()
NotificationConfigurationUpdateInput.model_rebuild()
NotificationChannelConfigurationInput.model_rebuild()
NotificationActivityScopeInput.model_rebuild()
PrivateKeysInput.model_rebuild()
ListPrivateKeysFilter.model_rebuild()
RemediatePrivateKeysInput.model_rebuild()
PublicKeysInput.model_rebuild()
ListPublicKeysFilter.model_rebuild()
RemediatePublicKeysInput.model_rebuild()
ListAssetComparisonReportsInput.model_rebuild()
SearchInput.model_rebuild()
SecretsInput.model_rebuild()
SecretCategoriesInput.model_rebuild()
HighProfileExploitInput.model_rebuild()
HighProfileExploitFilter.model_rebuild()
ActivityInput.model_rebuild()
FilesInput.model_rebuild()
ListFilesFilter.model_rebuild()
AssetsRelayInput.model_rebuild()
AssetsFilter.model_rebuild()
AssetOverviewInput.model_rebuild()
AssetOverviewFilter.model_rebuild()
AssetsInput.model_rebuild()
ListComponentFilter.model_rebuild()
AddDependencyInput.model_rebuild()
ModifyDependencyInput.model_rebuild()
AssetGroupMembersInput.model_rebuild()
AssetGroupsInput.model_rebuild()
GroupedDependenciesInput.model_rebuild()
DependencyInput.model_rebuild()
DependencyFilter.model_rebuild()
DependencyAnalyticFilter.model_rebuild()
GroupedDependencyFilter.model_rebuild()
ValueFilter.model_rebuild()
MisconfigurationsInput.model_rebuild()
MisconfigurationsFilter.model_rebuild()
CreateAcrInput.model_rebuild()
ReplaceAcrInput.model_rebuild()
UsersInput.model_rebuild()
CreateAssetVulnerabilityRemediationInput.model_rebuild()
CreateAssetVulnerabilityRemediationsInput.model_rebuild()
CreateAllAssetVulnerabilitiesRemediationInput.model_rebuild()
VulnerabilityOverviewInput.model_rebuild()
VulnerabilityOverviewFilter.model_rebuild()
PaginatedVulnerabilitiesInput.model_rebuild()
PaginatedDetailedVulnerabilitiesInput.model_rebuild()
DetailedVulnerabilityFilter.model_rebuild()
VulnerabilityFilter.model_rebuild()
