# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationSaveJiraSpaceWorkflowConfig(BaseModel):
    save_jira_space_workflow_config: (
        "MutationSaveJiraSpaceWorkflowConfigSaveJiraSpaceWorkflowConfig"
    ) = Field(alias="saveJiraSpaceWorkflowConfig")


class MutationSaveJiraSpaceWorkflowConfigSaveJiraSpaceWorkflowConfig(BaseModel):
    error: Optional[str]
    success: bool


MutationSaveJiraSpaceWorkflowConfig.model_rebuild()
