# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AcrEntityType, AcrResourceType


class MutationReplaceACR(BaseModel):
    replace_acr: "MutationReplaceACRReplaceAcr" = Field(alias="replaceACR")


class MutationReplaceACRReplaceAcr(BaseModel):
    new_acr: Optional["MutationReplaceACRReplaceAcrNewAcr"] = Field(alias="newAcr")
    replaced_acr: Optional["MutationReplaceACRReplaceAcrReplacedAcr"] = Field(
        alias="replacedAcr"
    )


class MutationReplaceACRReplaceAcrNewAcr(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    direct_permissions: list[str] = Field(alias="directPermissions")
    entity_id: str = Field(alias="entityId")
    entity_member_count: Optional[int] = Field(alias="entityMemberCount")
    entity_name: Optional[str] = Field(alias="entityName")
    entity_type: AcrEntityType = Field(alias="entityType")
    expires_at: Optional[str] = Field(alias="expiresAt")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    org_id: str = Field(alias="orgId")
    resource_id: Optional[str] = Field(alias="resourceId")
    resource_name: Optional[str] = Field(alias="resourceName")
    resource_type: AcrResourceType = Field(alias="resourceType")
    role_id: Optional[str] = Field(alias="roleId")
    role_name: Optional[str] = Field(alias="roleName")
    role_permissions: list[str] = Field(alias="rolePermissions")
    user_emails: list[str] = Field(alias="userEmails")


class MutationReplaceACRReplaceAcrReplacedAcr(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    direct_permissions: list[str] = Field(alias="directPermissions")
    entity_id: str = Field(alias="entityId")
    entity_member_count: Optional[int] = Field(alias="entityMemberCount")
    entity_name: Optional[str] = Field(alias="entityName")
    entity_type: AcrEntityType = Field(alias="entityType")
    expires_at: Optional[str] = Field(alias="expiresAt")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    org_id: str = Field(alias="orgId")
    resource_id: Optional[str] = Field(alias="resourceId")
    resource_name: Optional[str] = Field(alias="resourceName")
    resource_type: AcrResourceType = Field(alias="resourceType")
    role_id: Optional[str] = Field(alias="roleId")
    role_name: Optional[str] = Field(alias="roleName")
    role_permissions: list[str] = Field(alias="rolePermissions")
    user_emails: list[str] = Field(alias="userEmails")


MutationReplaceACR.model_rebuild()
MutationReplaceACRReplaceAcr.model_rebuild()
