# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationCreateAssetComparisonReport(BaseModel):
    create_asset_comparison_report: (
        "MutationCreateAssetComparisonReportCreateAssetComparisonReport"
    ) = Field(alias="createAssetComparisonReport")


class MutationCreateAssetComparisonReportCreateAssetComparisonReport(BaseModel):
    job_id: str = Field(alias="jobId")


MutationCreateAssetComparisonReport.model_rebuild()
