# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecretRemediationStatus


class MutationRemediateSecrets(BaseModel):
    remediate_secrets: Optional[
        list[Optional["MutationRemediateSecretsRemediateSecrets"]]
    ] = Field(alias="remediateSecrets")


class MutationRemediateSecretsRemediateSecrets(BaseModel):
    author: Optional[str]
    created_at: Optional[str] = Field(alias="createdAt")
    description: Optional[str]
    secret_id: Optional[str] = Field(alias="secretId")
    status: Optional[SecretRemediationStatus]


MutationRemediateSecrets.model_rebuild()
