# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationRemoveOrgUser(BaseModel):
    remove_org_user: "MutationRemoveOrgUserRemoveOrgUser" = Field(alias="removeOrgUser")


class MutationRemoveOrgUserRemoveOrgUser(BaseModel):
    success: bool
    user_id: str = Field(alias="userId")


MutationRemoveOrgUser.model_rebuild()
