# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationJiraIntegrationTestConnection(BaseModel):
    jira_integration_test_connection: (
        "MutationJiraIntegrationTestConnectionJiraIntegrationTestConnection"
    ) = Field(alias="jiraIntegrationTestConnection")


class MutationJiraIntegrationTestConnectionJiraIntegrationTestConnection(BaseModel):
    error: Optional[str]
    success: bool


MutationJiraIntegrationTestConnection.model_rebuild()
