# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationSetAssetsToAssetGroup(BaseModel):
    set_assets_to_asset_group: bool = Field(alias="setAssetsToAssetGroup")
