# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CryptoRemediationStatus


class MutationRemediatePrivateKeys(BaseModel):
    remediate_private_keys: list[
        Optional["MutationRemediatePrivateKeysRemediatePrivateKeys"]
    ] = Field(alias="remediatePrivateKeys")


class MutationRemediatePrivateKeysRemediatePrivateKeys(BaseModel):
    author: Optional[str]
    created_at: Optional[str] = Field(alias="createdAt")
    description: Optional[str]
    error_message: Optional[str] = Field(alias="errorMessage")
    private_key: "MutationRemediatePrivateKeysRemediatePrivateKeysPrivateKey" = Field(
        alias="privateKey"
    )
    status: CryptoRemediationStatus


class MutationRemediatePrivateKeysRemediatePrivateKeysPrivateKey(BaseModel):
    file_path: str = Field(alias="filePath")
    match_hash: str = Field(alias="matchHash")


MutationRemediatePrivateKeys.model_rebuild()
MutationRemediatePrivateKeysRemediatePrivateKeys.model_rebuild()
