# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationJiraIntegrationAddConnectedSpace(BaseModel):
    jira_integration_add_connected_space: (
        "MutationJiraIntegrationAddConnectedSpaceJiraIntegrationAddConnectedSpace"
    ) = Field(alias="jiraIntegrationAddConnectedSpace")


class MutationJiraIntegrationAddConnectedSpaceJiraIntegrationAddConnectedSpace(
    BaseModel
):
    error: Optional[str]
    success: bool


MutationJiraIntegrationAddConnectedSpace.model_rebuild()
