# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationAddAssetGroupsToAssets(BaseModel):
    add_asset_groups_to_assets: bool = Field(alias="addAssetGroupsToAssets")
