# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationDeleteNotificationConfiguration(BaseModel):
    delete_notification_configuration: bool = Field(
        alias="deleteNotificationConfiguration"
    )
