# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ActivityEntityType,
    NotificationActivityKind,
    NotificationActivityThresholdField,
    NotificationActivityThresholdOperator,
    NotificationConfigurationChannel,
    NotificationConfigurationType,
)


class MutationUpdateNotificationConfiguration(BaseModel):
    update_notification_configuration: Optional[
        "MutationUpdateNotificationConfigurationUpdateNotificationConfiguration"
    ] = Field(alias="updateNotificationConfiguration")


class MutationUpdateNotificationConfigurationUpdateNotificationConfiguration(BaseModel):
    id: Optional[str]
    activity_scopes: list[
        "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationActivityScopes"
    ] = Field(alias="activityScopes")
    channel: Optional[NotificationConfigurationChannel]
    channel_configuration: Optional[
        Annotated[
            Union[
                "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationWebhook",
                "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationEmail",
                "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationApplication",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="channelConfiguration")
    created_at: Optional[str] = Field(alias="createdAt")
    disabled: Optional[bool]
    inventory_scopes: list[
        "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationInventoryScopes"
    ] = Field(alias="inventoryScopes")
    name: Optional[str]
    silenced: Optional[bool]
    type: Optional[NotificationConfigurationType]
    updated_at: Optional[str] = Field(alias="updatedAt")
    updated_by: Optional[str] = Field(alias="updatedBy")


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationActivityScopes(
    BaseModel
):
    activity_type: Optional[NotificationActivityKind] = Field(alias="activityType")
    entity_type: Optional[ActivityEntityType] = Field(alias="entityType")
    threshold: Optional[
        "MutationUpdateNotificationConfigurationUpdateNotificationConfigurationActivityScopesThreshold"
    ]


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationActivityScopesThreshold(
    BaseModel
):
    key: NotificationActivityThresholdField
    operator: NotificationActivityThresholdOperator
    value: str


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationWebhook(
    BaseModel
):
    typename__: Literal["NotificationConfigurationWebhook"] = Field(alias="__typename")
    url: str


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationEmail(
    BaseModel
):
    typename__: Literal["NotificationConfigurationEmail"] = Field(alias="__typename")
    address: str


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationChannelConfigurationNotificationConfigurationApplication(
    BaseModel
):
    typename__: Literal["NotificationConfigurationApplication"] = Field(
        alias="__typename"
    )
    empty: Optional[bool] = Field(alias="_empty")


class MutationUpdateNotificationConfigurationUpdateNotificationConfigurationInventoryScopes(
    BaseModel
):
    asset_id: Optional[str] = Field(alias="assetId")
    group_id: Optional[str] = Field(alias="groupId")
    organization: Optional[bool]


MutationUpdateNotificationConfiguration.model_rebuild()
MutationUpdateNotificationConfigurationUpdateNotificationConfiguration.model_rebuild()
MutationUpdateNotificationConfigurationUpdateNotificationConfigurationActivityScopes.model_rebuild()
