# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import JiraIntegrationStatus, JiraSystemCheckStatus


class MutationJiraIntegrationReconnect(BaseModel):
    jira_integration_reconnect: (
        "MutationJiraIntegrationReconnectJiraIntegrationReconnect"
    ) = Field(alias="jiraIntegrationReconnect")


class MutationJiraIntegrationReconnectJiraIntegrationReconnect(BaseModel):
    api_connectivity_active: bool = Field(alias="apiConnectivityActive")
    connection_health: (
        "MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealth"
    ) = Field(alias="connectionHealth")
    instance_url: Optional[str] = Field(alias="instanceUrl")
    jira_app_installed_complete: bool = Field(alias="jiraAppInstalledComplete")
    jira_installation_id: Optional[str] = Field(alias="jiraInstallationId")
    last_updated: Optional[str] = Field(alias="lastUpdated")
    oauth_install_step_complete: bool = Field(alias="oauthInstallStepComplete")
    oauth_token_active: bool = Field(alias="oauthTokenActive")
    spaces_count: Optional[int] = Field(alias="spacesCount")
    status: JiraIntegrationStatus


class MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealth(
    BaseModel
):
    addable_spaces: list[
        "MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthAddableSpaces"
    ] = Field(alias="addableSpaces")
    connected_spaces: list[
        "MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthConnectedSpaces"
    ] = Field(alias="connectedSpaces")
    connection_status_label: str = Field(alias="connectionStatusLabel")
    instance_url: str = Field(alias="instanceUrl")
    metrics: "MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthMetrics"
    system_checks: list[
        "MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthSystemChecks"
    ] = Field(alias="systemChecks")


class MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthAddableSpaces(
    BaseModel
):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    selected: bool


class MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthConnectedSpaces(
    BaseModel
):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    category: str
    icon_color_index: int = Field(alias="iconColorIndex")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    project_key: str = Field(alias="projectKey")


class MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthMetrics(
    BaseModel
):
    connected_spaces: str = Field(alias="connectedSpaces")
    last_sync: str = Field(alias="lastSync")


class MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealthSystemChecks(
    BaseModel
):
    id: str
    description: str
    status: JiraSystemCheckStatus
    title: str


MutationJiraIntegrationReconnect.model_rebuild()
MutationJiraIntegrationReconnectJiraIntegrationReconnect.model_rebuild()
MutationJiraIntegrationReconnectJiraIntegrationReconnectConnectionHealth.model_rebuild()
