# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationJiraIntegrationCreateIssue(BaseModel):
    jira_integration_create_issue: (
        "MutationJiraIntegrationCreateIssueJiraIntegrationCreateIssue"
    ) = Field(alias="jiraIntegrationCreateIssue")


class MutationJiraIntegrationCreateIssueJiraIntegrationCreateIssue(BaseModel):
    error: Optional[str]
    success: bool
    ticket: Optional[
        "MutationJiraIntegrationCreateIssueJiraIntegrationCreateIssueTicket"
    ]


class MutationJiraIntegrationCreateIssueJiraIntegrationCreateIssueTicket(BaseModel):
    id: str
    assignee: Optional[str]
    project_id: str = Field(alias="projectId")
    status: str
    ticket_key: str = Field(alias="ticketKey")
    updated_at: str = Field(alias="updatedAt")
    url: str


MutationJiraIntegrationCreateIssue.model_rebuild()
MutationJiraIntegrationCreateIssueJiraIntegrationCreateIssue.model_rebuild()
