# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationDeleteSecurityGroup(BaseModel):
    delete_security_group: "MutationDeleteSecurityGroupDeleteSecurityGroup" = Field(
        alias="deleteSecurityGroup"
    )


class MutationDeleteSecurityGroupDeleteSecurityGroup(BaseModel):
    security_group_id: str = Field(alias="securityGroupId")
    success: bool


MutationDeleteSecurityGroup.model_rebuild()
