# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationBulkDeleteACRs(BaseModel):
    bulk_delete_ac_rs: "MutationBulkDeleteACRsBulkDeleteAcRs" = Field(
        alias="bulkDeleteACRs"
    )


class MutationBulkDeleteACRsBulkDeleteAcRs(BaseModel):
    success: bool


MutationBulkDeleteACRs.model_rebuild()
