# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationUpdateSecurityGroup(BaseModel):
    update_security_group: "MutationUpdateSecurityGroupUpdateSecurityGroup" = Field(
        alias="updateSecurityGroup"
    )


class MutationUpdateSecurityGroupUpdateSecurityGroup(BaseModel):
    security_group: Optional[
        "MutationUpdateSecurityGroupUpdateSecurityGroupSecurityGroup"
    ] = Field(alias="securityGroup")


class MutationUpdateSecurityGroupUpdateSecurityGroupSecurityGroup(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    description: Optional[str]
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    member_count: Optional[int] = Field(alias="memberCount")
    members: list["MutationUpdateSecurityGroupUpdateSecurityGroupSecurityGroupMembers"]
    name: str


class MutationUpdateSecurityGroupUpdateSecurityGroupSecurityGroupMembers(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


MutationUpdateSecurityGroup.model_rebuild()
MutationUpdateSecurityGroupUpdateSecurityGroup.model_rebuild()
MutationUpdateSecurityGroupUpdateSecurityGroupSecurityGroup.model_rebuild()
