# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationJiraIntegrationDeleteConnectedSpace(BaseModel):
    jira_integration_delete_connected_space: (
        "MutationJiraIntegrationDeleteConnectedSpaceJiraIntegrationDeleteConnectedSpace"
    ) = Field(alias="jiraIntegrationDeleteConnectedSpace")


class MutationJiraIntegrationDeleteConnectedSpaceJiraIntegrationDeleteConnectedSpace(
    BaseModel
):
    error: Optional[str]
    success: bool


MutationJiraIntegrationDeleteConnectedSpace.model_rebuild()
