# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CryptoRemediationStatus


class MutationRemediateCertificates(BaseModel):
    remediate_certificates: list[
        Optional["MutationRemediateCertificatesRemediateCertificates"]
    ] = Field(alias="remediateCertificates")


class MutationRemediateCertificatesRemediateCertificates(BaseModel):
    author: Optional[str]
    certificate: "MutationRemediateCertificatesRemediateCertificatesCertificate"
    created_at: Optional[str] = Field(alias="createdAt")
    description: Optional[str]
    error_message: Optional[str] = Field(alias="errorMessage")
    status: CryptoRemediationStatus


class MutationRemediateCertificatesRemediateCertificatesCertificate(BaseModel):
    file_path: str = Field(alias="filePath")
    sha_256: str = Field(alias="sha256")


MutationRemediateCertificates.model_rebuild()
MutationRemediateCertificatesRemediateCertificates.model_rebuild()
