# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationUpdateCustomRole(BaseModel):
    update_custom_role: "MutationUpdateCustomRoleUpdateCustomRole" = Field(
        alias="updateCustomRole"
    )


class MutationUpdateCustomRoleUpdateCustomRole(BaseModel):
    role: Optional["MutationUpdateCustomRoleUpdateCustomRoleRole"]


class MutationUpdateCustomRoleUpdateCustomRoleRole(BaseModel):
    id: str
    description: Optional[str]
    is_builtin: bool = Field(alias="isBuiltin")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_by_email: Optional[str] = Field(alias="lastModifiedByEmail")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    name: str
    org_id: str = Field(alias="orgId")
    permissions: list[str]
    precedence: Optional[int]


MutationUpdateCustomRole.model_rebuild()
MutationUpdateCustomRoleUpdateCustomRole.model_rebuild()
