# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationDeleteAssetComparisonReport(BaseModel):
    delete_asset_comparison_report: bool = Field(alias="deleteAssetComparisonReport")
