# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationRemoveSecurityGroupMember(BaseModel):
    remove_security_group_member: (
        "MutationRemoveSecurityGroupMemberRemoveSecurityGroupMember"
    ) = Field(alias="removeSecurityGroupMember")


class MutationRemoveSecurityGroupMemberRemoveSecurityGroupMember(BaseModel):
    security_group_id: str = Field(alias="securityGroupId")
    success: bool
    user_id: str = Field(alias="userId")


MutationRemoveSecurityGroupMember.model_rebuild()
