# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import RiseAIStatus


class MutationSubmitRiseAIAnalysis(BaseModel):
    submit_rise_ai_analysis: "MutationSubmitRiseAIAnalysisSubmitRiseAiAnalysis" = Field(
        alias="submitRiseAIAnalysis"
    )


class MutationSubmitRiseAIAnalysisSubmitRiseAiAnalysis(BaseModel):
    status: Optional[RiseAIStatus]


MutationSubmitRiseAIAnalysis.model_rebuild()
