# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationDeleteACR(BaseModel):
    delete_acr: "MutationDeleteACRDeleteAcr" = Field(alias="deleteACR")


class MutationDeleteACRDeleteAcr(BaseModel):
    acr_id: str = Field(alias="acrId")
    success: bool


MutationDeleteACR.model_rebuild()
