# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecurityGroupMemberSource


class MutationAddSecurityGroupMember(BaseModel):
    add_security_group_member: (
        "MutationAddSecurityGroupMemberAddSecurityGroupMember"
    ) = Field(alias="addSecurityGroupMember")


class MutationAddSecurityGroupMemberAddSecurityGroupMember(BaseModel):
    member: Optional["MutationAddSecurityGroupMemberAddSecurityGroupMemberMember"]


class MutationAddSecurityGroupMemberAddSecurityGroupMemberMember(BaseModel):
    accessible_asset_count: Optional[int] = Field(alias="accessibleAssetCount")
    created_time: Optional[str] = Field(alias="createdTime")
    display_name: Optional[str] = Field(alias="displayName")
    email: Optional[str]
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    source: SecurityGroupMemberSource
    user_id: Optional[str] = Field(alias="userId")


MutationAddSecurityGroupMember.model_rebuild()
MutationAddSecurityGroupMemberAddSecurityGroupMember.model_rebuild()
