# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AcrEntityType, AcrResourceType, OrgUserStatus


class MutationSetOrgUserStatus(BaseModel):
    set_org_user_status: "MutationSetOrgUserStatusSetOrgUserStatus" = Field(
        alias="setOrgUserStatus"
    )


class MutationSetOrgUserStatusSetOrgUserStatus(BaseModel):
    user: Optional["MutationSetOrgUserStatusSetOrgUserStatusUser"]


class MutationSetOrgUserStatusSetOrgUserStatusUser(BaseModel):
    id: str
    accessible_asset_count: Optional[int] = Field(alias="accessibleAssetCount")
    acrs: list["MutationSetOrgUserStatusSetOrgUserStatusUserAcrs"]
    created_time: Optional[str] = Field(alias="createdTime")
    disabled_at: Optional[str] = Field(alias="disabledAt")
    disabled_by: Optional[str] = Field(alias="disabledBy")
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    email_verified: bool = Field(alias="emailVerified")
    is_external: bool = Field(alias="isExternal")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    org_id: str = Field(alias="orgId")
    permission_count: Optional[int] = Field(alias="permissionCount")
    security_groups: list[
        "MutationSetOrgUserStatusSetOrgUserStatusUserSecurityGroups"
    ] = Field(alias="securityGroups")
    status: Optional[OrgUserStatus]


class MutationSetOrgUserStatusSetOrgUserStatusUserAcrs(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    direct_permissions: list[str] = Field(alias="directPermissions")
    entity_id: str = Field(alias="entityId")
    entity_member_count: Optional[int] = Field(alias="entityMemberCount")
    entity_name: Optional[str] = Field(alias="entityName")
    entity_type: AcrEntityType = Field(alias="entityType")
    expires_at: Optional[str] = Field(alias="expiresAt")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    org_id: str = Field(alias="orgId")
    resource_id: Optional[str] = Field(alias="resourceId")
    resource_name: Optional[str] = Field(alias="resourceName")
    resource_type: AcrResourceType = Field(alias="resourceType")
    role_id: Optional[str] = Field(alias="roleId")
    role_name: Optional[str] = Field(alias="roleName")
    role_permissions: list[str] = Field(alias="rolePermissions")
    user_emails: list[str] = Field(alias="userEmails")


class MutationSetOrgUserStatusSetOrgUserStatusUserSecurityGroups(BaseModel):
    id: str
    max_role_precedence: int = Field(alias="maxRolePrecedence")
    name: str


MutationSetOrgUserStatus.model_rebuild()
MutationSetOrgUserStatusSetOrgUserStatus.model_rebuild()
MutationSetOrgUserStatusSetOrgUserStatusUser.model_rebuild()
