# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationUpdateOrgLevelSettings(BaseModel):
    update_org_level_settings: Optional[
        "MutationUpdateOrgLevelSettingsUpdateOrgLevelSettings"
    ] = Field(alias="updateOrgLevelSettings")


class MutationUpdateOrgLevelSettingsUpdateOrgLevelSettings(BaseModel):
    err: Optional[str]


MutationUpdateOrgLevelSettings.model_rebuild()
