# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationDeleteCustomRole(BaseModel):
    delete_custom_role: "MutationDeleteCustomRoleDeleteCustomRole" = Field(
        alias="deleteCustomRole"
    )


class MutationDeleteCustomRoleDeleteCustomRole(BaseModel):
    role_id: str = Field(alias="roleId")
    success: bool


MutationDeleteCustomRole.model_rebuild()
