# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationJiraIntegrationSetStatusMappingAutoSync(BaseModel):
    jira_integration_set_status_mapping_auto_sync: (
        "MutationJiraIntegrationSetStatusMappingAutoSyncJiraIntegrationSetStatusMappingAutoSync"
    ) = Field(alias="jiraIntegrationSetStatusMappingAutoSync")


class MutationJiraIntegrationSetStatusMappingAutoSyncJiraIntegrationSetStatusMappingAutoSync(
    BaseModel
):
    error: Optional[str]
    success: bool


MutationJiraIntegrationSetStatusMappingAutoSync.model_rebuild()
