# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Annotated, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AssetAnalysisEventSelection,
    CertificateValidityPeriod,
    NewSBOMFindingsSelection,
    NotificationCategory,
    NotificationSettingsType,
    NotificationTimeframe,
    UserManagementEventSelection,
    VulnerabilitiesExploitsSelection,
    VulnerabilitiesSeveritiesSelection,
)


class MutationUpdateNotificationSettings(BaseModel):
    update_notification_settings: (
        "MutationUpdateNotificationSettingsUpdateNotificationSettings"
    ) = Field(alias="updateNotificationSettings")


class MutationUpdateNotificationSettingsUpdateNotificationSettings(BaseModel):
    allow_user_overrides: bool = Field(alias="allowUserOverrides")
    email_notifications_enabled: bool = Field(alias="emailNotificationsEnabled")
    notification_timeframe: NotificationTimeframe = Field(alias="notificationTimeframe")
    preferences: list[
        "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferences"
    ]


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferences(
    BaseModel
):
    category: NotificationCategory
    console: str
    console_enabled: bool = Field(alias="consoleEnabled")
    controls: list[
        Annotated[
            Union[
                "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsVulnerabilityControl",
                "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsCertificateControl",
                "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsAssetAnalysisControl",
                "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsSbomFindingsControl",
                "MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsUserManagementControl",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    email: str
    email_enabled: bool = Field(alias="emailEnabled")
    name: str
    type: NotificationSettingsType
    webhook: str
    webhook_enabled: bool = Field(alias="webhookEnabled")


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsVulnerabilityControl(
    BaseModel
):
    typename__: Literal["VulnerabilityControl"] = Field(alias="__typename")
    exploits: list[VulnerabilitiesExploitsSelection]
    severities: list[VulnerabilitiesSeveritiesSelection]


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsCertificateControl(
    BaseModel
):
    typename__: Literal["CertificateControl"] = Field(alias="__typename")
    max_validity: CertificateValidityPeriod = Field(alias="maxValidity")
    min_validity: CertificateValidityPeriod = Field(alias="minValidity")


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsAssetAnalysisControl(
    BaseModel
):
    typename__: Literal["AssetAnalysisControl"] = Field(alias="__typename")
    asset_analysis_control_events: list[AssetAnalysisEventSelection] = Field(
        alias="assetAnalysisControlEvents"
    )


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsSbomFindingsControl(
    BaseModel
):
    typename__: Literal["SbomFindingsControl"] = Field(alias="__typename")
    findings: list[NewSBOMFindingsSelection]


class MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferencesControlsUserManagementControl(
    BaseModel
):
    typename__: Literal["UserManagementControl"] = Field(alias="__typename")
    user_management_control_events: list[UserManagementEventSelection] = Field(
        alias="userManagementControlEvents"
    )


MutationUpdateNotificationSettings.model_rebuild()
MutationUpdateNotificationSettingsUpdateNotificationSettings.model_rebuild()
MutationUpdateNotificationSettingsUpdateNotificationSettingsPreferences.model_rebuild()
