# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationCreateSecurityGroup(BaseModel):
    create_security_group: "MutationCreateSecurityGroupCreateSecurityGroup" = Field(
        alias="createSecurityGroup"
    )


class MutationCreateSecurityGroupCreateSecurityGroup(BaseModel):
    security_group: Optional[
        "MutationCreateSecurityGroupCreateSecurityGroupSecurityGroup"
    ] = Field(alias="securityGroup")


class MutationCreateSecurityGroupCreateSecurityGroupSecurityGroup(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    description: Optional[str]
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    member_count: Optional[int] = Field(alias="memberCount")
    members: list["MutationCreateSecurityGroupCreateSecurityGroupSecurityGroupMembers"]
    name: str


class MutationCreateSecurityGroupCreateSecurityGroupSecurityGroupMembers(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


MutationCreateSecurityGroup.model_rebuild()
MutationCreateSecurityGroupCreateSecurityGroup.model_rebuild()
MutationCreateSecurityGroupCreateSecurityGroupSecurityGroup.model_rebuild()
