# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class MutationRemoveAllAssetGroupsFromAssets(BaseModel):
    remove_all_asset_groups_from_assets: bool = Field(
        alias="removeAllAssetGroupsFromAssets"
    )
