# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CryptoRemediationStatus


class MutationRemediatePublicKeys(BaseModel):
    remediate_public_keys: list[
        Optional["MutationRemediatePublicKeysRemediatePublicKeys"]
    ] = Field(alias="remediatePublicKeys")


class MutationRemediatePublicKeysRemediatePublicKeys(BaseModel):
    asset_id: Optional[str] = Field(alias="assetId")
    author: str
    created_at: str = Field(alias="createdAt")
    description: Optional[str]
    public_key: "MutationRemediatePublicKeysRemediatePublicKeysPublicKey" = Field(
        alias="publicKey"
    )
    public_key_id: str = Field(alias="publicKeyId")
    status: CryptoRemediationStatus


class MutationRemediatePublicKeysRemediatePublicKeysPublicKey(BaseModel):
    file_path: str = Field(alias="filePath")
    match_hash: str = Field(alias="matchHash")


MutationRemediatePublicKeys.model_rebuild()
MutationRemediatePublicKeysRemediatePublicKeys.model_rebuild()
