# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    JiraSetupActionType,
    JiraSetupMode,
    JiraSetupStep,
    JiraSetupStepStatus,
)


class MutationJiraIntegrationSetupAction(BaseModel):
    jira_integration_setup_action: (
        "MutationJiraIntegrationSetupActionJiraIntegrationSetupAction"
    ) = Field(alias="jiraIntegrationSetupAction")


class MutationJiraIntegrationSetupActionJiraIntegrationSetupAction(BaseModel):
    app_version: Optional[str] = Field(alias="appVersion")
    available_sites: list[
        "MutationJiraIntegrationSetupActionJiraIntegrationSetupActionAvailableSites"
    ] = Field(alias="availableSites")
    available_spaces: list[
        "MutationJiraIntegrationSetupActionJiraIntegrationSetupActionAvailableSpaces"
    ] = Field(alias="availableSpaces")
    current_step: JiraSetupStep = Field(alias="currentStep")
    error: Optional["MutationJiraIntegrationSetupActionJiraIntegrationSetupActionError"]
    instance_url: Optional[str] = Field(alias="instanceUrl")
    mode: JiraSetupMode
    primary_action: (
        "MutationJiraIntegrationSetupActionJiraIntegrationSetupActionPrimaryAction"
    ) = Field(alias="primaryAction")
    reconnect_summary: Optional[
        "MutationJiraIntegrationSetupActionJiraIntegrationSetupActionReconnectSummary"
    ] = Field(alias="reconnectSummary")
    selected_site_id: Optional[str] = Field(alias="selectedSiteId")
    selected_space_ids: list[str] = Field(alias="selectedSpaceIds")
    steps: list["MutationJiraIntegrationSetupActionJiraIntegrationSetupActionSteps"]


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionAvailableSites(
    BaseModel
):
    id: str
    selectable: bool
    url: str


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionAvailableSpaces(
    BaseModel
):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    selected: bool


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionError(BaseModel):
    message: str
    title: str


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionPrimaryAction(
    BaseModel
):
    action_type: JiraSetupActionType = Field(alias="actionType")
    disabled: bool
    label: str
    loading: bool
    url: Optional[str]


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionReconnectSummary(
    BaseModel
):
    connected_spaces_count: int = Field(alias="connectedSpacesCount")


class MutationJiraIntegrationSetupActionJiraIntegrationSetupActionSteps(BaseModel):
    description: Optional[str]
    detail: Optional[str]
    status: JiraSetupStepStatus
    step: JiraSetupStep
    title: str


MutationJiraIntegrationSetupAction.model_rebuild()
MutationJiraIntegrationSetupActionJiraIntegrationSetupAction.model_rebuild()
