# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ActivityEntityType,
    NotificationActivityKind,
    NotificationActivityThresholdField,
    NotificationActivityThresholdOperator,
    NotificationConfigurationChannel,
    NotificationConfigurationType,
)


class MutationCreateNotificationConfiguration(BaseModel):
    create_notification_configuration: Optional[
        "MutationCreateNotificationConfigurationCreateNotificationConfiguration"
    ] = Field(alias="createNotificationConfiguration")


class MutationCreateNotificationConfigurationCreateNotificationConfiguration(BaseModel):
    id: Optional[str]
    activity_scopes: list[
        "MutationCreateNotificationConfigurationCreateNotificationConfigurationActivityScopes"
    ] = Field(alias="activityScopes")
    channel: Optional[NotificationConfigurationChannel]
    channel_configuration: Optional[
        Annotated[
            Union[
                "MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationWebhook",
                "MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationEmail",
                "MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationApplication",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="channelConfiguration")
    created_at: Optional[str] = Field(alias="createdAt")
    disabled: Optional[bool]
    inventory_scopes: list[
        "MutationCreateNotificationConfigurationCreateNotificationConfigurationInventoryScopes"
    ] = Field(alias="inventoryScopes")
    name: Optional[str]
    silenced: Optional[bool]
    type: Optional[NotificationConfigurationType]
    updated_at: Optional[str] = Field(alias="updatedAt")
    updated_by: Optional[str] = Field(alias="updatedBy")


class MutationCreateNotificationConfigurationCreateNotificationConfigurationActivityScopes(
    BaseModel
):
    activity_type: Optional[NotificationActivityKind] = Field(alias="activityType")
    entity_type: Optional[ActivityEntityType] = Field(alias="entityType")
    threshold: Optional[
        "MutationCreateNotificationConfigurationCreateNotificationConfigurationActivityScopesThreshold"
    ]


class MutationCreateNotificationConfigurationCreateNotificationConfigurationActivityScopesThreshold(
    BaseModel
):
    key: NotificationActivityThresholdField
    operator: NotificationActivityThresholdOperator
    value: str


class MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationWebhook(
    BaseModel
):
    typename__: Literal["NotificationConfigurationWebhook"] = Field(alias="__typename")
    url: str


class MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationEmail(
    BaseModel
):
    typename__: Literal["NotificationConfigurationEmail"] = Field(alias="__typename")
    address: str


class MutationCreateNotificationConfigurationCreateNotificationConfigurationChannelConfigurationNotificationConfigurationApplication(
    BaseModel
):
    typename__: Literal["NotificationConfigurationApplication"] = Field(
        alias="__typename"
    )
    empty: Optional[bool] = Field(alias="_empty")


class MutationCreateNotificationConfigurationCreateNotificationConfigurationInventoryScopes(
    BaseModel
):
    asset_id: Optional[str] = Field(alias="assetId")
    group_id: Optional[str] = Field(alias="groupId")
    organization: Optional[bool]


MutationCreateNotificationConfiguration.model_rebuild()
MutationCreateNotificationConfigurationCreateNotificationConfiguration.model_rebuild()
MutationCreateNotificationConfigurationCreateNotificationConfigurationActivityScopes.model_rebuild()
