# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MutationAssetModifyDependency(BaseModel):
    asset: Optional["MutationAssetModifyDependencyAsset"]


class MutationAssetModifyDependencyAsset(BaseModel):
    modify_dependency: Optional[
        "MutationAssetModifyDependencyAssetModifyDependency"
    ] = Field(alias="modifyDependency")


class MutationAssetModifyDependencyAssetModifyDependency(BaseModel):
    err: Optional[str]


MutationAssetModifyDependency.model_rebuild()
MutationAssetModifyDependencyAsset.model_rebuild()
