# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AssetType, ProcessingStatus
from .fragments import AssetAnalyticLite, PageInfoFields, RiskFields


class QueryAssetsRelayLite(BaseModel):
    assets_relay: Optional["QueryAssetsRelayLiteAssetsRelay"] = Field(
        alias="assetsRelay"
    )


class QueryAssetsRelayLiteAssetsRelay(BaseModel):
    edges: Optional[list[Optional["QueryAssetsRelayLiteAssetsRelayEdges"]]]
    page_info: "QueryAssetsRelayLiteAssetsRelayPageInfo" = Field(alias="pageInfo")


class QueryAssetsRelayLiteAssetsRelayEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryAssetsRelayLiteAssetsRelayEdgesNode"]


class QueryAssetsRelayLiteAssetsRelayEdgesNode(BaseModel):
    id: Optional[str]
    name: Optional[str]
    product: Optional[str]
    vendor: Optional[str]
    version: Optional[str]
    type: Optional[AssetType]
    status: Optional[ProcessingStatus]
    created_at: Optional[str] = Field(alias="createdAt")
    updated_at: Optional[str] = Field(alias="updatedAt")
    risk: Optional["QueryAssetsRelayLiteAssetsRelayEdgesNodeRisk"]
    analytic: Optional["QueryAssetsRelayLiteAssetsRelayEdgesNodeAnalytic"]


class QueryAssetsRelayLiteAssetsRelayEdgesNodeRisk(RiskFields):
    pass


class QueryAssetsRelayLiteAssetsRelayEdgesNodeAnalytic(AssetAnalyticLite):
    pass


class QueryAssetsRelayLiteAssetsRelayPageInfo(PageInfoFields):
    pass


QueryAssetsRelayLite.model_rebuild()
QueryAssetsRelayLiteAssetsRelay.model_rebuild()
QueryAssetsRelayLiteAssetsRelayEdges.model_rebuild()
QueryAssetsRelayLiteAssetsRelayEdgesNode.model_rebuild()
