# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListAssetComparisonReports(BaseModel):
    list_asset_comparison_reports: (
        "QueryListAssetComparisonReportsListAssetComparisonReports"
    ) = Field(alias="listAssetComparisonReports")


class QueryListAssetComparisonReportsListAssetComparisonReports(BaseModel):
    edges: list["QueryListAssetComparisonReportsListAssetComparisonReportsEdges"]
    page_info: "QueryListAssetComparisonReportsListAssetComparisonReportsPageInfo" = (
        Field(alias="pageInfo")
    )
    total_count: int = Field(alias="totalCount")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdges(BaseModel):
    cursor: str
    node: "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNode"


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNode(BaseModel):
    asset_a_info: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeAssetAInfo"
    ] = Field(alias="assetAInfo")
    asset_b_info: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeAssetBInfo"
    ] = Field(alias="assetBInfo")
    comparison_report_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummary"
    ] = Field(alias="comparisonReportSummary")
    completed_at: Optional[str] = Field(alias="completedAt")
    component_diff: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiff"
    ] = Field(alias="componentDiff")
    created_at: Optional[str] = Field(alias="createdAt")
    created_by: Optional[str] = Field(alias="createdBy")
    report_id: str = Field(alias="reportId")
    river_job_id: Optional[str] = Field(alias="riverJobId")
    vulnerability_diff: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiff"
    ] = Field(alias="vulnerabilityDiff")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeAssetAInfo(
    BaseModel
):
    analysis_created_at: Optional[str] = Field(alias="analysisCreatedAt")
    analysis_id: Optional[str] = Field(alias="analysisId")
    asset_created_at: Optional[str] = Field(alias="assetCreatedAt")
    asset_id: Optional[str] = Field(alias="assetId")
    asset_type: Optional[str] = Field(alias="assetType")
    name: Optional[str]
    org_id: Optional[str] = Field(alias="orgId")
    product: Optional[str]
    uploaded_by: Optional[str] = Field(alias="uploadedBy")
    vendor: Optional[str]
    version: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeAssetBInfo(
    BaseModel
):
    analysis_created_at: Optional[str] = Field(alias="analysisCreatedAt")
    analysis_id: Optional[str] = Field(alias="analysisId")
    asset_created_at: Optional[str] = Field(alias="assetCreatedAt")
    asset_id: Optional[str] = Field(alias="assetId")
    asset_type: Optional[str] = Field(alias="assetType")
    name: Optional[str]
    org_id: Optional[str] = Field(alias="orgId")
    product: Optional[str]
    uploaded_by: Optional[str] = Field(alias="uploadedBy")
    vendor: Optional[str]
    version: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummary(
    BaseModel
):
    asset_a_credentials_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetACredentialsSummary"
    ] = Field(alias="assetACredentialsSummary")
    asset_a_cryptography_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetACryptographySummary"
    ] = Field(alias="assetACryptographySummary")
    asset_a_license_issue_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetALicenseIssueSummary"
    ] = Field(alias="assetALicenseIssueSummary")
    asset_a_misconfigurations_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetAMisconfigurationsSummary"
    ] = Field(alias="assetAMisconfigurationsSummary")
    asset_a_vulnerability_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetAVulnerabilitySummary"
    ] = Field(alias="assetAVulnerabilitySummary")
    asset_b_credentials_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBCredentialsSummary"
    ] = Field(alias="assetBCredentialsSummary")
    asset_b_cryptography_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBCryptographySummary"
    ] = Field(alias="assetBCryptographySummary")
    asset_b_license_issue_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBLicenseIssueSummary"
    ] = Field(alias="assetBLicenseIssueSummary")
    asset_b_misconfigurations_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBMisconfigurationsSummary"
    ] = Field(alias="assetBMisconfigurationsSummary")
    asset_b_vulnerability_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBVulnerabilitySummary"
    ] = Field(alias="assetBVulnerabilitySummary")
    inventory_comparison_summary: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryInventoryComparisonSummary"
    ] = Field(alias="inventoryComparisonSummary")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetACredentialsSummary(
    BaseModel
):
    total_cracked_accounts: Optional[int] = Field(alias="totalCrackedAccounts")
    total_cracked_hashes: Optional[int] = Field(alias="totalCrackedHashes")
    total_exposed_secrets: Optional[int] = Field(alias="totalExposedSecrets")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetACryptographySummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_not_applicable: Optional[int] = Field(alias="totalNotApplicable")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetALicenseIssueSummary(
    BaseModel
):
    total_copyleft: Optional[int] = Field(alias="totalCopyleft")
    total_licenses: Optional[int] = Field(alias="totalLicenses")
    total_relational_conflict: Optional[int] = Field(alias="totalRelationalConflict")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetAMisconfigurationsSummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetAVulnerabilitySummary(
    BaseModel
):
    total_critical: Optional[int] = Field(alias="totalCritical")
    total_high: Optional[int] = Field(alias="totalHigh")
    total_kev: Optional[int] = Field(alias="totalKev")
    total_low: Optional[int] = Field(alias="totalLow")
    total_medium: Optional[int] = Field(alias="totalMedium")
    total_poc: Optional[int] = Field(alias="totalPoc")
    total_reachable: Optional[int] = Field(alias="totalReachable")
    total_weaponized: Optional[int] = Field(alias="totalWeaponized")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBCredentialsSummary(
    BaseModel
):
    total_cracked_accounts: Optional[int] = Field(alias="totalCrackedAccounts")
    total_cracked_hashes: Optional[int] = Field(alias="totalCrackedHashes")
    total_exposed_secrets: Optional[int] = Field(alias="totalExposedSecrets")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBCryptographySummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_not_applicable: Optional[int] = Field(alias="totalNotApplicable")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBLicenseIssueSummary(
    BaseModel
):
    total_copyleft: Optional[int] = Field(alias="totalCopyleft")
    total_licenses: Optional[int] = Field(alias="totalLicenses")
    total_relational_conflict: Optional[int] = Field(alias="totalRelationalConflict")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBMisconfigurationsSummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryAssetBVulnerabilitySummary(
    BaseModel
):
    total_critical: Optional[int] = Field(alias="totalCritical")
    total_high: Optional[int] = Field(alias="totalHigh")
    total_kev: Optional[int] = Field(alias="totalKev")
    total_low: Optional[int] = Field(alias="totalLow")
    total_medium: Optional[int] = Field(alias="totalMedium")
    total_poc: Optional[int] = Field(alias="totalPoc")
    total_reachable: Optional[int] = Field(alias="totalReachable")
    total_weaponized: Optional[int] = Field(alias="totalWeaponized")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummaryInventoryComparisonSummary(
    BaseModel
):
    binaries_in_a_not_in_b: Optional[int] = Field(alias="binariesInANotInB")
    binaries_in_b_not_in_a: Optional[int] = Field(alias="binariesInBNotInA")
    components_in_a_not_in_b: Optional[int] = Field(alias="componentsInANotInB")
    components_in_b_not_in_a: Optional[int] = Field(alias="componentsInBNotInA")
    files_in_a_not_in_b: Optional[int] = Field(alias="filesInANotInB")
    files_in_b_not_in_a: Optional[int] = Field(alias="filesInBNotInA")
    licenses_in_a_not_in_b: Optional[int] = Field(alias="licensesInANotInB")
    licenses_in_b_not_in_a: Optional[int] = Field(alias="licensesInBNotInA")
    total_overlapping_binaries: Optional[int] = Field(alias="totalOverlappingBinaries")
    total_overlapping_components: Optional[int] = Field(
        alias="totalOverlappingComponents"
    )
    total_overlapping_files: Optional[int] = Field(alias="totalOverlappingFiles")
    total_overlapping_licenses: Optional[int] = Field(alias="totalOverlappingLicenses")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiff(
    BaseModel
):
    asset_a_type_counts: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffAssetATypeCounts"
    ] = Field(alias="assetATypeCounts")
    asset_b_type_counts: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffAssetBTypeCounts"
    ] = Field(alias="assetBTypeCounts")
    in_a_not_in_b: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffInANotInB"
            ]
        ]
    ] = Field(alias="inANotInB")
    in_a_not_in_b_reachable_count: Optional[int] = Field(
        alias="inANotInBReachableCount"
    )
    in_b_not_in_a: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffInBNotInA"
            ]
        ]
    ] = Field(alias="inBNotInA")
    in_b_not_in_a_reachable_count: Optional[int] = Field(
        alias="inBNotInAReachableCount"
    )
    overlap: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffOverlap"
            ]
        ]
    ]
    overlap_reachable_count: Optional[int] = Field(alias="overlapReachableCount")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffAssetATypeCounts(
    BaseModel
):
    ai_model: int = Field(alias="aiModel")
    application: int
    container: int
    device: int
    framework: int
    kernel: int
    kernel_module: int = Field(alias="kernelModule")
    library: int
    os: int
    package: int


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffAssetBTypeCounts(
    BaseModel
):
    ai_model: int = Field(alias="aiModel")
    application: int
    container: int
    device: int
    framework: int
    kernel: int
    kernel_module: int = Field(alias="kernelModule")
    library: int
    os: int
    package: int


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffInANotInB(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffInBNotInA(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiffOverlap(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiff(
    BaseModel
):
    asset_vulnerability_remediation_diff: Optional[
        "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffAssetVulnerabilityRemediationDiff"
    ] = Field(alias="assetVulnerabilityRemediationDiff")
    in_a_not_in_b: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffInANotInB"
            ]
        ]
    ] = Field(alias="inANotInB")
    in_a_not_in_b_kev_count: Optional[int] = Field(alias="inANotInBKevCount")
    in_a_not_in_b_reachable_count: Optional[int] = Field(
        alias="inANotInBReachableCount"
    )
    in_b_not_in_a: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffInBNotInA"
            ]
        ]
    ] = Field(alias="inBNotInA")
    in_b_not_in_a_kev_count: Optional[int] = Field(alias="inBNotInAKevCount")
    in_b_not_in_a_reachable_count: Optional[int] = Field(
        alias="inBNotInAReachableCount"
    )
    overlap: Optional[
        list[
            Optional[
                "QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffOverlap"
            ]
        ]
    ]
    overlap_kev_count: Optional[int] = Field(alias="overlapKevCount")
    overlap_reachable_count: Optional[int] = Field(alias="overlapReachableCount")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffAssetVulnerabilityRemediationDiff(
    BaseModel
):
    total_resolved_a: Optional[int] = Field(alias="totalResolvedA")
    total_resolved_a_not_present_in_b: Optional[int] = Field(
        alias="totalResolvedANotPresentInB"
    )
    total_resolved_b: Optional[int] = Field(alias="totalResolvedB")
    total_resolved_b_not_present_in_a: Optional[int] = Field(
        alias="totalResolvedBNotPresentInA"
    )
    total_resolved_in_a_present_in_b: Optional[int] = Field(
        alias="totalResolvedInAPresentInB"
    )
    total_resolved_in_b_present_in_a: Optional[int] = Field(
        alias="totalResolvedInBPresentInA"
    )
    total_tracked_a: Optional[int] = Field(alias="totalTrackedA")
    total_tracked_b: Optional[int] = Field(alias="totalTrackedB")


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffInANotInB(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffInBNotInA(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiffOverlap(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryListAssetComparisonReportsListAssetComparisonReportsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListAssetComparisonReports.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReports.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReportsEdges.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNode.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComparisonReportSummary.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeComponentDiff.model_rebuild()
QueryListAssetComparisonReportsListAssetComparisonReportsEdgesNodeVulnerabilityDiff.model_rebuild()
