# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectTeams(BaseModel):
    jira_project_teams: list["QueryJiraProjectTeamsJiraProjectTeams"] = Field(
        alias="jiraProjectTeams"
    )


class QueryJiraProjectTeamsJiraProjectTeams(BaseModel):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    display_name: str = Field(alias="displayName")


QueryJiraProjectTeams.model_rebuild()
