# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListEntityAssets(BaseModel):
    list_entity_assets: "QueryListEntityAssetsListEntityAssets" = Field(
        alias="listEntityAssets"
    )


class QueryListEntityAssetsListEntityAssets(BaseModel):
    edges: Optional[list[Optional["QueryListEntityAssetsListEntityAssetsEdges"]]]
    page_info: "QueryListEntityAssetsListEntityAssetsPageInfo" = Field(alias="pageInfo")


class QueryListEntityAssetsListEntityAssetsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListEntityAssetsListEntityAssetsEdgesNode"]


class QueryListEntityAssetsListEntityAssetsEdgesNode(BaseModel):
    id: str
    asset_type: str = Field(alias="assetType")
    name: str


class QueryListEntityAssetsListEntityAssetsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListEntityAssets.model_rebuild()
QueryListEntityAssetsListEntityAssets.model_rebuild()
QueryListEntityAssetsListEntityAssetsEdges.model_rebuild()
