# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListAiProviders(BaseModel):
    list_ai_providers: Optional["QueryListAiProvidersListAiProviders"] = Field(
        alias="listAiProviders"
    )


class QueryListAiProvidersListAiProviders(BaseModel):
    ai_providers: list[str] = Field(alias="aiProviders")


QueryListAiProviders.model_rebuild()
