# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryPrivateKeyExternalFilters(BaseModel):
    private_key_external_filters: Optional[
        "QueryPrivateKeyExternalFiltersPrivateKeyExternalFilters"
    ] = Field(alias="privateKeyExternalFilters")


class QueryPrivateKeyExternalFiltersPrivateKeyExternalFilters(BaseModel):
    total_classical: Optional[int] = Field(alias="totalClassical")
    total_pqc: Optional[int] = Field(alias="totalPqc")


QueryPrivateKeyExternalFilters.model_rebuild()
