# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import JiraIntegrationStatus, JiraSystemCheckStatus


class QueryJiraIntegration(BaseModel):
    jira_integration: "QueryJiraIntegrationJiraIntegration" = Field(
        alias="jiraIntegration"
    )


class QueryJiraIntegrationJiraIntegration(BaseModel):
    api_connectivity_active: bool = Field(alias="apiConnectivityActive")
    connection_health: "QueryJiraIntegrationJiraIntegrationConnectionHealth" = Field(
        alias="connectionHealth"
    )
    instance_url: Optional[str] = Field(alias="instanceUrl")
    jira_app_installed_complete: bool = Field(alias="jiraAppInstalledComplete")
    jira_installation_id: Optional[str] = Field(alias="jiraInstallationId")
    last_updated: Optional[str] = Field(alias="lastUpdated")
    oauth_install_step_complete: bool = Field(alias="oauthInstallStepComplete")
    oauth_token_active: bool = Field(alias="oauthTokenActive")
    spaces_count: Optional[int] = Field(alias="spacesCount")
    status: JiraIntegrationStatus


class QueryJiraIntegrationJiraIntegrationConnectionHealth(BaseModel):
    addable_spaces: list[
        "QueryJiraIntegrationJiraIntegrationConnectionHealthAddableSpaces"
    ] = Field(alias="addableSpaces")
    connected_spaces: list[
        "QueryJiraIntegrationJiraIntegrationConnectionHealthConnectedSpaces"
    ] = Field(alias="connectedSpaces")
    connection_status_label: str = Field(alias="connectionStatusLabel")
    instance_url: str = Field(alias="instanceUrl")
    metrics: "QueryJiraIntegrationJiraIntegrationConnectionHealthMetrics"
    system_checks: list[
        "QueryJiraIntegrationJiraIntegrationConnectionHealthSystemChecks"
    ] = Field(alias="systemChecks")


class QueryJiraIntegrationJiraIntegrationConnectionHealthAddableSpaces(BaseModel):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    selected: bool


class QueryJiraIntegrationJiraIntegrationConnectionHealthConnectedSpaces(BaseModel):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    category: str
    icon_color_index: int = Field(alias="iconColorIndex")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    project_key: str = Field(alias="projectKey")


class QueryJiraIntegrationJiraIntegrationConnectionHealthMetrics(BaseModel):
    connected_spaces: str = Field(alias="connectedSpaces")
    last_sync: str = Field(alias="lastSync")


class QueryJiraIntegrationJiraIntegrationConnectionHealthSystemChecks(BaseModel):
    id: str
    description: str
    status: JiraSystemCheckStatus
    title: str


QueryJiraIntegration.model_rebuild()
QueryJiraIntegrationJiraIntegration.model_rebuild()
QueryJiraIntegrationJiraIntegrationConnectionHealth.model_rebuild()
