# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AcrResourceType


class QueryGetResourcePermissions(BaseModel):
    get_resource_permissions: Optional[
        "QueryGetResourcePermissionsGetResourcePermissions"
    ] = Field(alias="getResourcePermissions")


class QueryGetResourcePermissionsGetResourcePermissions(BaseModel):
    permissions: list[str]
    resource_id: str = Field(alias="resourceId")
    resource_type: AcrResourceType = Field(alias="resourceType")


QueryGetResourcePermissions.model_rebuild()
