# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryPublicKeyExternalFilters(BaseModel):
    public_key_external_filters: Optional[
        "QueryPublicKeyExternalFiltersPublicKeyExternalFilters"
    ] = Field(alias="publicKeyExternalFilters")


class QueryPublicKeyExternalFiltersPublicKeyExternalFilters(BaseModel):
    total_classical: Optional[int] = Field(alias="totalClassical")
    total_pqc: Optional[int] = Field(alias="totalPqc")


QueryPublicKeyExternalFilters.model_rebuild()
