# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class QueryCaasAvailability(BaseModel):
    caas_availability: bool = Field(alias="caasAvailability")
