# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EvidenceEdgeType, EvidenceEntryType


class QueryGetCertificateReachability(BaseModel):
    get_certificate_reachability: Optional[
        list["QueryGetCertificateReachabilityGetCertificateReachability"]
    ] = Field(alias="getCertificateReachability")


class QueryGetCertificateReachabilityGetCertificateReachability(BaseModel):
    cve_id: Optional[str] = Field(alias="cveId")
    entry_point: Optional[str] = Field(alias="entryPoint")
    entry_type: Optional[EvidenceEntryType] = Field(alias="entryType")
    scripts: Optional[
        list[
            Optional["QueryGetCertificateReachabilityGetCertificateReachabilityScripts"]
        ]
    ]
    user: Optional[str]


class QueryGetCertificateReachabilityGetCertificateReachabilityScripts(BaseModel):
    detail: Optional[str]
    edge_type: Optional[EvidenceEdgeType] = Field(alias="edgeType")
    invocation: Optional[str]
    path: Optional[str]


QueryGetCertificateReachability.model_rebuild()
QueryGetCertificateReachabilityGetCertificateReachability.model_rebuild()
