# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AcrEntityType, AcrResourceType


class QueryListMyACRs(BaseModel):
    list_my_ac_rs: "QueryListMyACRsListMyAcRs" = Field(alias="listMyACRs")


class QueryListMyACRsListMyAcRs(BaseModel):
    edges: Optional[list[Optional["QueryListMyACRsListMyAcRsEdges"]]]
    page_info: "QueryListMyACRsListMyAcRsPageInfo" = Field(alias="pageInfo")


class QueryListMyACRsListMyAcRsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListMyACRsListMyAcRsEdgesNode"]


class QueryListMyACRsListMyAcRsEdgesNode(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    direct_permissions: list[str] = Field(alias="directPermissions")
    entity_id: str = Field(alias="entityId")
    entity_member_count: Optional[int] = Field(alias="entityMemberCount")
    entity_name: Optional[str] = Field(alias="entityName")
    entity_type: AcrEntityType = Field(alias="entityType")
    expires_at: Optional[str] = Field(alias="expiresAt")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    org_id: str = Field(alias="orgId")
    resource_id: Optional[str] = Field(alias="resourceId")
    resource_name: Optional[str] = Field(alias="resourceName")
    resource_type: AcrResourceType = Field(alias="resourceType")
    role_id: Optional[str] = Field(alias="roleId")
    role_name: Optional[str] = Field(alias="roleName")
    role_permissions: list[str] = Field(alias="rolePermissions")
    user_emails: list[str] = Field(alias="userEmails")


class QueryListMyACRsListMyAcRsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListMyACRs.model_rebuild()
QueryListMyACRsListMyAcRs.model_rebuild()
QueryListMyACRsListMyAcRsEdges.model_rebuild()
