# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGetAssetComparisonReport(BaseModel):
    get_asset_comparison_report: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReport"
    ] = Field(alias="getAssetComparisonReport")


class QueryGetAssetComparisonReportGetAssetComparisonReport(BaseModel):
    asset_a_info: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportAssetAInfo"
    ] = Field(alias="assetAInfo")
    asset_b_info: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportAssetBInfo"
    ] = Field(alias="assetBInfo")
    comparison_report_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummary"
    ] = Field(alias="comparisonReportSummary")
    completed_at: Optional[str] = Field(alias="completedAt")
    component_diff: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiff"
    ] = Field(alias="componentDiff")
    created_at: Optional[str] = Field(alias="createdAt")
    created_by: Optional[str] = Field(alias="createdBy")
    report_id: str = Field(alias="reportId")
    river_job_id: Optional[str] = Field(alias="riverJobId")
    vulnerability_diff: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiff"
    ] = Field(alias="vulnerabilityDiff")


class QueryGetAssetComparisonReportGetAssetComparisonReportAssetAInfo(BaseModel):
    analysis_created_at: Optional[str] = Field(alias="analysisCreatedAt")
    analysis_id: Optional[str] = Field(alias="analysisId")
    asset_created_at: Optional[str] = Field(alias="assetCreatedAt")
    asset_id: Optional[str] = Field(alias="assetId")
    asset_type: Optional[str] = Field(alias="assetType")
    name: Optional[str]
    org_id: Optional[str] = Field(alias="orgId")
    product: Optional[str]
    uploaded_by: Optional[str] = Field(alias="uploadedBy")
    vendor: Optional[str]
    version: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportAssetBInfo(BaseModel):
    analysis_created_at: Optional[str] = Field(alias="analysisCreatedAt")
    analysis_id: Optional[str] = Field(alias="analysisId")
    asset_created_at: Optional[str] = Field(alias="assetCreatedAt")
    asset_id: Optional[str] = Field(alias="assetId")
    asset_type: Optional[str] = Field(alias="assetType")
    name: Optional[str]
    org_id: Optional[str] = Field(alias="orgId")
    product: Optional[str]
    uploaded_by: Optional[str] = Field(alias="uploadedBy")
    vendor: Optional[str]
    version: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummary(
    BaseModel
):
    asset_a_credentials_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetACredentialsSummary"
    ] = Field(alias="assetACredentialsSummary")
    asset_a_cryptography_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetACryptographySummary"
    ] = Field(alias="assetACryptographySummary")
    asset_a_license_issue_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetALicenseIssueSummary"
    ] = Field(alias="assetALicenseIssueSummary")
    asset_a_misconfigurations_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetAMisconfigurationsSummary"
    ] = Field(alias="assetAMisconfigurationsSummary")
    asset_a_vulnerability_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetAVulnerabilitySummary"
    ] = Field(alias="assetAVulnerabilitySummary")
    asset_b_credentials_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBCredentialsSummary"
    ] = Field(alias="assetBCredentialsSummary")
    asset_b_cryptography_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBCryptographySummary"
    ] = Field(alias="assetBCryptographySummary")
    asset_b_license_issue_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBLicenseIssueSummary"
    ] = Field(alias="assetBLicenseIssueSummary")
    asset_b_misconfigurations_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBMisconfigurationsSummary"
    ] = Field(alias="assetBMisconfigurationsSummary")
    asset_b_vulnerability_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBVulnerabilitySummary"
    ] = Field(alias="assetBVulnerabilitySummary")
    inventory_comparison_summary: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryInventoryComparisonSummary"
    ] = Field(alias="inventoryComparisonSummary")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetACredentialsSummary(
    BaseModel
):
    total_cracked_accounts: Optional[int] = Field(alias="totalCrackedAccounts")
    total_cracked_hashes: Optional[int] = Field(alias="totalCrackedHashes")
    total_exposed_secrets: Optional[int] = Field(alias="totalExposedSecrets")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetACryptographySummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_not_applicable: Optional[int] = Field(alias="totalNotApplicable")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetALicenseIssueSummary(
    BaseModel
):
    total_copyleft: Optional[int] = Field(alias="totalCopyleft")
    total_licenses: Optional[int] = Field(alias="totalLicenses")
    total_relational_conflict: Optional[int] = Field(alias="totalRelationalConflict")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetAMisconfigurationsSummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetAVulnerabilitySummary(
    BaseModel
):
    total_critical: Optional[int] = Field(alias="totalCritical")
    total_high: Optional[int] = Field(alias="totalHigh")
    total_kev: Optional[int] = Field(alias="totalKev")
    total_low: Optional[int] = Field(alias="totalLow")
    total_medium: Optional[int] = Field(alias="totalMedium")
    total_poc: Optional[int] = Field(alias="totalPoc")
    total_reachable: Optional[int] = Field(alias="totalReachable")
    total_weaponized: Optional[int] = Field(alias="totalWeaponized")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBCredentialsSummary(
    BaseModel
):
    total_cracked_accounts: Optional[int] = Field(alias="totalCrackedAccounts")
    total_cracked_hashes: Optional[int] = Field(alias="totalCrackedHashes")
    total_exposed_secrets: Optional[int] = Field(alias="totalExposedSecrets")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBCryptographySummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_not_applicable: Optional[int] = Field(alias="totalNotApplicable")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBLicenseIssueSummary(
    BaseModel
):
    total_copyleft: Optional[int] = Field(alias="totalCopyleft")
    total_licenses: Optional[int] = Field(alias="totalLicenses")
    total_relational_conflict: Optional[int] = Field(alias="totalRelationalConflict")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBMisconfigurationsSummary(
    BaseModel
):
    total_failed: Optional[int] = Field(alias="totalFailed")
    total_passed: Optional[int] = Field(alias="totalPassed")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryAssetBVulnerabilitySummary(
    BaseModel
):
    total_critical: Optional[int] = Field(alias="totalCritical")
    total_high: Optional[int] = Field(alias="totalHigh")
    total_kev: Optional[int] = Field(alias="totalKev")
    total_low: Optional[int] = Field(alias="totalLow")
    total_medium: Optional[int] = Field(alias="totalMedium")
    total_poc: Optional[int] = Field(alias="totalPoc")
    total_reachable: Optional[int] = Field(alias="totalReachable")
    total_weaponized: Optional[int] = Field(alias="totalWeaponized")


class QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummaryInventoryComparisonSummary(
    BaseModel
):
    binaries_in_a_not_in_b: Optional[int] = Field(alias="binariesInANotInB")
    binaries_in_b_not_in_a: Optional[int] = Field(alias="binariesInBNotInA")
    components_in_a_not_in_b: Optional[int] = Field(alias="componentsInANotInB")
    components_in_b_not_in_a: Optional[int] = Field(alias="componentsInBNotInA")
    files_in_a_not_in_b: Optional[int] = Field(alias="filesInANotInB")
    files_in_b_not_in_a: Optional[int] = Field(alias="filesInBNotInA")
    licenses_in_a_not_in_b: Optional[int] = Field(alias="licensesInANotInB")
    licenses_in_b_not_in_a: Optional[int] = Field(alias="licensesInBNotInA")
    total_overlapping_binaries: Optional[int] = Field(alias="totalOverlappingBinaries")
    total_overlapping_components: Optional[int] = Field(
        alias="totalOverlappingComponents"
    )
    total_overlapping_files: Optional[int] = Field(alias="totalOverlappingFiles")
    total_overlapping_licenses: Optional[int] = Field(alias="totalOverlappingLicenses")


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiff(BaseModel):
    asset_a_type_counts: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffAssetATypeCounts"
    ] = Field(alias="assetATypeCounts")
    asset_b_type_counts: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffAssetBTypeCounts"
    ] = Field(alias="assetBTypeCounts")
    in_a_not_in_b: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffInANotInB"
            ]
        ]
    ] = Field(alias="inANotInB")
    in_a_not_in_b_reachable_count: Optional[int] = Field(
        alias="inANotInBReachableCount"
    )
    in_b_not_in_a: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffInBNotInA"
            ]
        ]
    ] = Field(alias="inBNotInA")
    in_b_not_in_a_reachable_count: Optional[int] = Field(
        alias="inBNotInAReachableCount"
    )
    overlap: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffOverlap"
            ]
        ]
    ]
    overlap_reachable_count: Optional[int] = Field(alias="overlapReachableCount")


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffAssetATypeCounts(
    BaseModel
):
    ai_model: int = Field(alias="aiModel")
    application: int
    container: int
    device: int
    framework: int
    kernel: int
    kernel_module: int = Field(alias="kernelModule")
    library: int
    os: int
    package: int


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffAssetBTypeCounts(
    BaseModel
):
    ai_model: int = Field(alias="aiModel")
    application: int
    container: int
    device: int
    framework: int
    kernel: int
    kernel_module: int = Field(alias="kernelModule")
    library: int
    os: int
    package: int


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffInANotInB(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffInBNotInA(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiffOverlap(
    BaseModel
):
    critical_sevs: Optional[int] = Field(alias="criticalSevs")
    high_sevs: Optional[int] = Field(alias="highSevs")
    licenses: Optional[list[Optional[str]]]
    low_sevs: Optional[int] = Field(alias="lowSevs")
    medium_sevs: Optional[int] = Field(alias="mediumSevs")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    reachable: Optional[bool]
    total_vulns: Optional[int] = Field(alias="totalVulns")
    type: Optional[str]
    version: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiff(BaseModel):
    asset_vulnerability_remediation_diff: Optional[
        "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiff"
    ] = Field(alias="assetVulnerabilityRemediationDiff")
    in_a_not_in_b: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffInANotInB"
            ]
        ]
    ] = Field(alias="inANotInB")
    in_a_not_in_b_kev_count: Optional[int] = Field(alias="inANotInBKevCount")
    in_a_not_in_b_reachable_count: Optional[int] = Field(
        alias="inANotInBReachableCount"
    )
    in_b_not_in_a: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffInBNotInA"
            ]
        ]
    ] = Field(alias="inBNotInA")
    in_b_not_in_a_kev_count: Optional[int] = Field(alias="inBNotInAKevCount")
    in_b_not_in_a_reachable_count: Optional[int] = Field(
        alias="inBNotInAReachableCount"
    )
    overlap: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffOverlap"
            ]
        ]
    ]
    overlap_kev_count: Optional[int] = Field(alias="overlapKevCount")
    overlap_reachable_count: Optional[int] = Field(alias="overlapReachableCount")


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiff(
    BaseModel
):
    total_resolved_a: Optional[int] = Field(alias="totalResolvedA")
    total_resolved_a_not_present_in_b: Optional[int] = Field(
        alias="totalResolvedANotPresentInB"
    )
    total_resolved_b: Optional[int] = Field(alias="totalResolvedB")
    total_resolved_b_not_present_in_a: Optional[int] = Field(
        alias="totalResolvedBNotPresentInA"
    )
    total_resolved_in_a_present_in_b: Optional[int] = Field(
        alias="totalResolvedInAPresentInB"
    )
    total_resolved_in_b_present_in_a: Optional[int] = Field(
        alias="totalResolvedInBPresentInA"
    )
    total_tracked_a: Optional[int] = Field(alias="totalTrackedA")
    total_tracked_b: Optional[int] = Field(alias="totalTrackedB")
    vulnerabilities_marked_resolved_in_a: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesMarkedResolvedInA"
            ]
        ]
    ] = Field(alias="vulnerabilitiesMarkedResolvedInA")
    vulnerabilities_marked_resolved_in_b: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesMarkedResolvedInB"
            ]
        ]
    ] = Field(alias="vulnerabilitiesMarkedResolvedInB")
    vulnerabilities_resolved_in_a: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInA"
            ]
        ]
    ] = Field(alias="vulnerabilitiesResolvedInA")
    vulnerabilities_resolved_in_a_present_in_b: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInAPresentInB"
            ]
        ]
    ] = Field(alias="vulnerabilitiesResolvedInAPresentInB")
    vulnerabilities_resolved_in_b: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInB"
            ]
        ]
    ] = Field(alias="vulnerabilitiesResolvedInB")
    vulnerabilities_resolved_in_b_present_in_a: Optional[
        list[
            Optional[
                "QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInBPresentInA"
            ]
        ]
    ] = Field(alias="vulnerabilitiesResolvedInBPresentInA")


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesMarkedResolvedInA(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesMarkedResolvedInB(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInA(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInAPresentInB(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInB(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiffVulnerabilitiesResolvedInBPresentInA(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffInANotInB(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffInBNotInA(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


class QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffOverlap(
    BaseModel
):
    cisa_kev: Optional[bool] = Field(alias="cisaKev")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    cve_id: Optional[str] = Field(alias="cveId")
    cvss_score: Optional[float] = Field(alias="cvssScore")
    exploit_maturity: Optional[str] = Field(alias="exploitMaturity")
    reachable: Optional[bool]
    severity: Optional[str]


QueryGetAssetComparisonReport.model_rebuild()
QueryGetAssetComparisonReportGetAssetComparisonReport.model_rebuild()
QueryGetAssetComparisonReportGetAssetComparisonReportComparisonReportSummary.model_rebuild()
QueryGetAssetComparisonReportGetAssetComparisonReportComponentDiff.model_rebuild()
QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiff.model_rebuild()
QueryGetAssetComparisonReportGetAssetComparisonReportVulnerabilityDiffAssetVulnerabilityRemediationDiff.model_rebuild()
