# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryCertificateExternalFilters(BaseModel):
    certificate_external_filters: Optional[
        "QueryCertificateExternalFiltersCertificateExternalFilters"
    ] = Field(alias="certificateExternalFilters")


class QueryCertificateExternalFiltersCertificateExternalFilters(BaseModel):
    total_classical: Optional[int] = Field(alias="totalClassical")
    total_pqc: Optional[int] = Field(alias="totalPqc")


QueryCertificateExternalFilters.model_rebuild()
