# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    JiraSetupActionType,
    JiraSetupMode,
    JiraSetupStep,
    JiraSetupStepStatus,
)


class QueryJiraIntegrationSetup(BaseModel):
    jira_integration_setup: "QueryJiraIntegrationSetupJiraIntegrationSetup" = Field(
        alias="jiraIntegrationSetup"
    )


class QueryJiraIntegrationSetupJiraIntegrationSetup(BaseModel):
    app_version: Optional[str] = Field(alias="appVersion")
    available_sites: list[
        "QueryJiraIntegrationSetupJiraIntegrationSetupAvailableSites"
    ] = Field(alias="availableSites")
    available_spaces: list[
        "QueryJiraIntegrationSetupJiraIntegrationSetupAvailableSpaces"
    ] = Field(alias="availableSpaces")
    current_step: JiraSetupStep = Field(alias="currentStep")
    error: Optional["QueryJiraIntegrationSetupJiraIntegrationSetupError"]
    instance_url: Optional[str] = Field(alias="instanceUrl")
    mode: JiraSetupMode
    primary_action: "QueryJiraIntegrationSetupJiraIntegrationSetupPrimaryAction" = (
        Field(alias="primaryAction")
    )
    reconnect_summary: Optional[
        "QueryJiraIntegrationSetupJiraIntegrationSetupReconnectSummary"
    ] = Field(alias="reconnectSummary")
    selected_site_id: Optional[str] = Field(alias="selectedSiteId")
    selected_space_ids: list[str] = Field(alias="selectedSpaceIds")
    steps: list["QueryJiraIntegrationSetupJiraIntegrationSetupSteps"]


class QueryJiraIntegrationSetupJiraIntegrationSetupAvailableSites(BaseModel):
    id: str
    selectable: bool
    url: str


class QueryJiraIntegrationSetupJiraIntegrationSetupAvailableSpaces(BaseModel):
    id: str
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    name: str
    open_tickets_count: int = Field(alias="openTicketsCount")
    selected: bool


class QueryJiraIntegrationSetupJiraIntegrationSetupError(BaseModel):
    message: str
    title: str


class QueryJiraIntegrationSetupJiraIntegrationSetupPrimaryAction(BaseModel):
    action_type: JiraSetupActionType = Field(alias="actionType")
    disabled: bool
    label: str
    loading: bool
    url: Optional[str]


class QueryJiraIntegrationSetupJiraIntegrationSetupReconnectSummary(BaseModel):
    connected_spaces_count: int = Field(alias="connectedSpacesCount")


class QueryJiraIntegrationSetupJiraIntegrationSetupSteps(BaseModel):
    description: Optional[str]
    detail: Optional[str]
    status: JiraSetupStepStatus
    step: JiraSetupStep
    title: str


QueryJiraIntegrationSetup.model_rebuild()
QueryJiraIntegrationSetupJiraIntegrationSetup.model_rebuild()
