# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel
from .enums import JiraStatusCategory, VexStatus


class QueryJiraSpaceWorkflowConfig(BaseModel):
    jira_space_workflow_config: (
        "QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfig"
    ) = Field(alias="jiraSpaceWorkflowConfig")


class QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfig(BaseModel):
    issue_type_id: str = Field(alias="issueTypeId")
    jira_statuses: list[
        "QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfigJiraStatuses"
    ] = Field(alias="jiraStatuses")
    mappings: list["QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfigMappings"]
    netrise_statuses: list[VexStatus] = Field(alias="netriseStatuses")
    resolution_status_ids: list[str] = Field(alias="resolutionStatusIds")
    space_id: str = Field(alias="spaceId")


class QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfigJiraStatuses(BaseModel):
    id: str
    category: JiraStatusCategory
    name: str


class QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfigMappings(BaseModel):
    jira_status_id: str = Field(alias="jiraStatusId")
    netrise_status_id: str = Field(alias="netriseStatusId")


QueryJiraSpaceWorkflowConfig.model_rebuild()
QueryJiraSpaceWorkflowConfigJiraSpaceWorkflowConfig.model_rebuild()
