# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from datetime import datetime
from typing import Annotated, Any, Optional

from pydantic import BeforeValidator, Field

from .base_model import BaseModel
from .custom_scalars import parse_datetime
from .enums import LicenseIssueSeverity, LicenseIssueStatus


class QueryLicenseIssues(BaseModel):
    license_issues: Optional["QueryLicenseIssuesLicenseIssues"] = Field(
        alias="licenseIssues"
    )


class QueryLicenseIssuesLicenseIssues(BaseModel):
    edges: list["QueryLicenseIssuesLicenseIssuesEdges"]
    page_info: "QueryLicenseIssuesLicenseIssuesPageInfo" = Field(alias="pageInfo")


class QueryLicenseIssuesLicenseIssuesEdges(BaseModel):
    cursor: Optional[str]
    node: "QueryLicenseIssuesLicenseIssuesEdgesNode"


class QueryLicenseIssuesLicenseIssuesEdgesNode(BaseModel):
    component_id: Optional[str] = Field(alias="componentId")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    evidence: Optional["QueryLicenseIssuesLicenseIssuesEdgesNodeEvidence"]
    issue_description: Optional[str] = Field(alias="issueDescription")
    issue_id: str = Field(alias="issueId")
    issue_name: str = Field(alias="issueName")
    last_modified: Optional[Annotated[datetime, BeforeValidator(parse_datetime)]] = (
        Field(alias="lastModified")
    )
    license: Optional["QueryLicenseIssuesLicenseIssuesEdgesNodeLicense"]
    potential_solution: Optional[str] = Field(alias="potentialSolution")
    remediation: Optional["QueryLicenseIssuesLicenseIssuesEdgesNodeRemediation"]
    severity: Optional[LicenseIssueSeverity]
    status: LicenseIssueStatus


class QueryLicenseIssuesLicenseIssuesEdgesNodeEvidence(BaseModel):
    children: Optional[Any]
    component_id: Optional[str] = Field(alias="componentId")
    license_name: Optional[str] = Field(alias="licenseName")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    spdx_id: Optional[str] = Field(alias="spdxId")
    vendor: Optional[str]
    version: Optional[str]


class QueryLicenseIssuesLicenseIssuesEdgesNodeLicense(BaseModel):
    additional_counts: Optional[
        "QueryLicenseIssuesLicenseIssuesEdgesNodeLicenseAdditionalCounts"
    ] = Field(alias="additionalCounts")
    additional_info_urls_list: Optional[list[Optional[str]]] = Field(
        alias="additionalInfoUrlsList"
    )
    license_name: Optional[str] = Field(alias="licenseName")
    license_notes: Optional[str] = Field(alias="licenseNotes")
    license_type: Optional[str] = Field(alias="licenseType")
    license_url: Optional[str] = Field(alias="licenseUrl")
    spdx_id: Optional[str] = Field(alias="spdxId")
    url: Optional[str]


class QueryLicenseIssuesLicenseIssuesEdgesNodeLicenseAdditionalCounts(BaseModel):
    associated_components: Optional[int] = Field(alias="associatedComponents")
    issues: Optional[int]


class QueryLicenseIssuesLicenseIssuesEdgesNodeRemediation(BaseModel):
    created_time: Optional[Annotated[datetime, BeforeValidator(parse_datetime)]] = (
        Field(alias="createdTime")
    )
    detail: Optional[str]
    user: Optional[str]


class QueryLicenseIssuesLicenseIssuesPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryLicenseIssues.model_rebuild()
QueryLicenseIssuesLicenseIssues.model_rebuild()
QueryLicenseIssuesLicenseIssuesEdges.model_rebuild()
QueryLicenseIssuesLicenseIssuesEdgesNode.model_rebuild()
QueryLicenseIssuesLicenseIssuesEdgesNodeLicense.model_rebuild()
