# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    RiskCategory,
    SecretCategory,
    SecretRemediationStatus,
    SecretSeverity,
    SecretType,
)


class QuerySecret(BaseModel):
    secret: Optional["QuerySecretSecret"]


class QuerySecretSecret(BaseModel):
    id: str
    category: SecretCategory
    category_label: Optional[str] = Field(alias="categoryLabel")
    correlations: Optional[list["QuerySecretSecretCorrelations"]]
    correlations_count: int = Field(alias="correlationsCount")
    current_remediation: Optional["QuerySecretSecretCurrentRemediation"] = Field(
        alias="currentRemediation"
    )
    description: Optional[str]
    file_path: Optional[str] = Field(alias="filePath")
    raw_secret: Optional[str] = Field(alias="rawSecret")
    remediation_status: Optional[SecretRemediationStatus] = Field(
        alias="remediationStatus"
    )
    sanitized_secret: Optional[str] = Field(alias="sanitizedSecret")
    severity: SecretSeverity
    subtype: Optional[str]
    type: Optional[SecretType]


class QuerySecretSecretCorrelations(BaseModel):
    artifact: Optional[str]
    asset_id: Optional[str] = Field(alias="assetId")
    asset_name: Optional[str] = Field(alias="assetName")
    location: Optional[str]
    risk: Optional["QuerySecretSecretCorrelationsRisk"]
    updated_at: Optional[str] = Field(alias="updatedAt")


class QuerySecretSecretCorrelationsRisk(BaseModel):
    category: Optional[RiskCategory]
    raw_score: Optional[float] = Field(alias="rawScore")
    score: Optional[float]


class QuerySecretSecretCurrentRemediation(BaseModel):
    author: Optional[str]
    created_at: Optional[str] = Field(alias="createdAt")
    description: Optional[str]
    secret_id: Optional[str] = Field(alias="secretId")
    status: Optional[SecretRemediationStatus]


QuerySecret.model_rebuild()
QuerySecretSecret.model_rebuild()
QuerySecretSecretCorrelations.model_rebuild()
