# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraSpaceIssueFields(BaseModel):
    jira_space_issue_fields: list["QueryJiraSpaceIssueFieldsJiraSpaceIssueFields"] = (
        Field(alias="jiraSpaceIssueFields")
    )


class QueryJiraSpaceIssueFieldsJiraSpaceIssueFields(BaseModel):
    allowed_values: list[
        "QueryJiraSpaceIssueFieldsJiraSpaceIssueFieldsAllowedValues"
    ] = Field(alias="allowedValues")
    item_type: str = Field(alias="itemType")
    key: str
    name: str
    required: bool
    schema_custom: Optional[str] = Field(alias="schemaCustom")
    schema_type: str = Field(alias="schemaType")
    supported: bool
    unsupported_required: bool = Field(alias="unsupportedRequired")


class QueryJiraSpaceIssueFieldsJiraSpaceIssueFieldsAllowedValues(BaseModel):
    id: str
    value: str


QueryJiraSpaceIssueFields.model_rebuild()
QueryJiraSpaceIssueFieldsJiraSpaceIssueFields.model_rebuild()
