# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from datetime import datetime
from typing import Annotated, Optional

from pydantic import BeforeValidator, Field

from .base_model import BaseModel
from .custom_scalars import parse_datetime
from .enums import ComponentSubType, ComponentType, IdentifiedViaCategory
from .fragments import AssetAnalyticLite, PageInfoFields


class QueryDependenciesLite(BaseModel):
    dependencies: Optional["QueryDependenciesLiteDependencies"]


class QueryDependenciesLiteDependencies(BaseModel):
    edges: Optional[list[Optional["QueryDependenciesLiteDependenciesEdges"]]]
    page_info: "QueryDependenciesLiteDependenciesPageInfo" = Field(alias="pageInfo")


class QueryDependenciesLiteDependenciesEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryDependenciesLiteDependenciesEdgesNode"]


class QueryDependenciesLiteDependenciesEdgesNode(BaseModel):
    id: str
    submit_datetime: Optional[Annotated[datetime, BeforeValidator(parse_datetime)]] = (
        Field(alias="submitDatetime")
    )
    identified_via: Optional[list[Optional[IdentifiedViaCategory]]] = Field(
        alias="identifiedVia"
    )
    correlations_count: Optional[int] = Field(alias="correlationsCount")
    dependency: "QueryDependenciesLiteDependenciesEdgesNodeDependency"
    analytic: "QueryDependenciesLiteDependenciesEdgesNodeAnalytic"


class QueryDependenciesLiteDependenciesEdgesNodeDependency(BaseModel):
    id: str
    name: str
    vendor: Optional[str]
    product: Optional[str]
    license: Optional[list[Optional[str]]]
    purls: Optional[list[Optional[str]]]
    type: ComponentType
    subtype: Optional[ComponentSubType]
    path: Optional[str]
    version: Optional["QueryDependenciesLiteDependenciesEdgesNodeDependencyVersion"]


class QueryDependenciesLiteDependenciesEdgesNodeDependencyVersion(BaseModel):
    id: Optional[str]
    is_concrete: bool = Field(alias="isConcrete")


class QueryDependenciesLiteDependenciesEdgesNodeAnalytic(AssetAnalyticLite):
    pass


class QueryDependenciesLiteDependenciesPageInfo(PageInfoFields):
    pass


QueryDependenciesLite.model_rebuild()
QueryDependenciesLiteDependencies.model_rebuild()
QueryDependenciesLiteDependenciesEdges.model_rebuild()
QueryDependenciesLiteDependenciesEdgesNode.model_rebuild()
QueryDependenciesLiteDependenciesEdgesNodeDependency.model_rebuild()
