# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import CvssPreferred, PageInfoFields


class QueryDetailedVulnerabilitiesLite(BaseModel):
    detailed_vulnerabilities: Optional[
        "QueryDetailedVulnerabilitiesLiteDetailedVulnerabilities"
    ] = Field(alias="detailedVulnerabilities")


class QueryDetailedVulnerabilitiesLiteDetailedVulnerabilities(BaseModel):
    edges: Optional[
        list[Optional["QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdges"]]
    ]
    page_info: "QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesPageInfo" = (
        Field(alias="pageInfo")
    )


class QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdgesNode"]


class QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdgesNode(BaseModel):
    id: Optional[str]
    severity: Optional[str]
    created_datetime: Optional[str] = Field(alias="createdDatetime")
    updated_datetime: Optional[str] = Field(alias="updatedDatetime")
    processed_datetime: Optional[str] = Field(alias="processedDatetime")
    description: Optional[str]
    impact_v_31: Optional[
        "QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdgesNodeImpactV31"
    ] = Field(alias="impactV31")


class QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdgesNodeImpactV31(
    CvssPreferred
):
    pass


class QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesPageInfo(PageInfoFields):
    pass


QueryDetailedVulnerabilitiesLite.model_rebuild()
QueryDetailedVulnerabilitiesLiteDetailedVulnerabilities.model_rebuild()
QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdges.model_rebuild()
QueryDetailedVulnerabilitiesLiteDetailedVulnerabilitiesEdgesNode.model_rebuild()
