# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AssetOverviewRiskCategory, VulnerabilityRemediationStatus


class QueryRemediatedVulnerabilitiesByAsset(BaseModel):
    remediated_vulnerabilities_by_asset: Optional[
        "QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAsset"
    ] = Field(alias="remediatedVulnerabilitiesByAsset")


class QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAsset(BaseModel):
    edges: Optional[
        list[
            Optional[
                "QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetEdges"
            ]
        ]
    ]
    page_info: (
        "QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetPageInfo"
    ) = Field(alias="pageInfo")


class QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetEdges(
    BaseModel
):
    cursor: Optional[str]
    node: Optional[
        "QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetEdgesNode"
    ]


class QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetEdgesNode(
    BaseModel
):
    asset_id: Optional[str] = Field(alias="assetId")
    asset_name: Optional[str] = Field(alias="assetName")
    asset_status: Optional[AssetOverviewRiskCategory] = Field(alias="assetStatus")
    asset_vendor: Optional[str] = Field(alias="assetVendor")
    remediation_count: int = Field(alias="remediationCount")
    remediation_status: Optional[VulnerabilityRemediationStatus] = Field(
        alias="remediationStatus"
    )


class QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetPageInfo(
    BaseModel
):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryRemediatedVulnerabilitiesByAsset.model_rebuild()
QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAsset.model_rebuild()
QueryRemediatedVulnerabilitiesByAssetRemediatedVulnerabilitiesByAssetEdges.model_rebuild()
