# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import RiskCategory


class QueryListAssetCorrelations(BaseModel):
    list_asset_correlations: "QueryListAssetCorrelationsListAssetCorrelations" = Field(
        alias="listAssetCorrelations"
    )


class QueryListAssetCorrelationsListAssetCorrelations(BaseModel):
    edges: Optional[
        list[Optional["QueryListAssetCorrelationsListAssetCorrelationsEdges"]]
    ]
    page_info: "QueryListAssetCorrelationsListAssetCorrelationsPageInfo" = Field(
        alias="pageInfo"
    )


class QueryListAssetCorrelationsListAssetCorrelationsEdges(BaseModel):
    cursor: Optional[str]
    node: "QueryListAssetCorrelationsListAssetCorrelationsEdgesNode"


class QueryListAssetCorrelationsListAssetCorrelationsEdgesNode(BaseModel):
    artifact: Optional[str]
    asset_id: Optional[str] = Field(alias="assetId")
    asset_name: Optional[str] = Field(alias="assetName")
    location: Optional[str]
    risk: Optional["QueryListAssetCorrelationsListAssetCorrelationsEdgesNodeRisk"]
    updated_at: Optional[str] = Field(alias="updatedAt")


class QueryListAssetCorrelationsListAssetCorrelationsEdgesNodeRisk(BaseModel):
    category: Optional[RiskCategory]
    raw_score: Optional[float] = Field(alias="rawScore")
    score: Optional[float]


class QueryListAssetCorrelationsListAssetCorrelationsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListAssetCorrelations.model_rebuild()
QueryListAssetCorrelationsListAssetCorrelations.model_rebuild()
QueryListAssetCorrelationsListAssetCorrelationsEdges.model_rebuild()
QueryListAssetCorrelationsListAssetCorrelationsEdgesNode.model_rebuild()
