# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from pydantic import Field

from .base_model import BaseModel


class QuerySecretsSummary(BaseModel):
    secrets_summary: "QuerySecretsSummarySecretsSummary" = Field(alias="secretsSummary")


class QuerySecretsSummarySecretsSummary(BaseModel):
    high: int
    invalid: int
    low: int
    medium: int
    total: int


QuerySecretsSummary.model_rebuild()
