# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecretCategory, SecretRemediationStatus, SecretSeverity


class QuerySecretCategoriesSummary(BaseModel):
    secret_categories_summary: Optional[
        list[Optional["QuerySecretCategoriesSummarySecretCategoriesSummary"]]
    ] = Field(alias="secretCategoriesSummary")


class QuerySecretCategoriesSummarySecretCategoriesSummary(BaseModel):
    category: Optional[SecretCategory]
    category_label: Optional[str] = Field(alias="categoryLabel")
    remediation_status_counts: Optional[
        list[
            Optional[
                "QuerySecretCategoriesSummarySecretCategoriesSummaryRemediationStatusCounts"
            ]
        ]
    ] = Field(alias="remediationStatusCounts")
    severity_counts: Optional[
        list[
            Optional[
                "QuerySecretCategoriesSummarySecretCategoriesSummarySeverityCounts"
            ]
        ]
    ] = Field(alias="severityCounts")


class QuerySecretCategoriesSummarySecretCategoriesSummaryRemediationStatusCounts(
    BaseModel
):
    count: Optional[int]
    status: Optional[SecretRemediationStatus]


class QuerySecretCategoriesSummarySecretCategoriesSummarySeverityCounts(BaseModel):
    count: Optional[int]
    severity: Optional[SecretSeverity]


QuerySecretCategoriesSummary.model_rebuild()
QuerySecretCategoriesSummarySecretCategoriesSummary.model_rebuild()
