# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListRoles(BaseModel):
    list_roles: "QueryListRolesListRoles" = Field(alias="listRoles")


class QueryListRolesListRoles(BaseModel):
    edges: Optional[list[Optional["QueryListRolesListRolesEdges"]]]
    page_info: "QueryListRolesListRolesPageInfo" = Field(alias="pageInfo")


class QueryListRolesListRolesEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListRolesListRolesEdgesNode"]


class QueryListRolesListRolesEdgesNode(BaseModel):
    id: str
    description: Optional[str]
    is_builtin: bool = Field(alias="isBuiltin")
    last_modified_by: Optional[str] = Field(alias="lastModifiedBy")
    last_modified_by_email: Optional[str] = Field(alias="lastModifiedByEmail")
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    name: str
    org_id: str = Field(alias="orgId")
    permissions: list[str]
    precedence: Optional[int]


class QueryListRolesListRolesPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListRoles.model_rebuild()
QueryListRolesListRoles.model_rebuild()
QueryListRolesListRolesEdges.model_rebuild()
