# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import NotificationParser, NotificationType


class QueryNotifications(BaseModel):
    notifications: "QueryNotificationsNotifications"


class QueryNotificationsNotifications(BaseModel):
    edges: Optional[list[Optional["QueryNotificationsNotificationsEdges"]]]
    page_info: "QueryNotificationsNotificationsPageInfo" = Field(alias="pageInfo")


class QueryNotificationsNotificationsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryNotificationsNotificationsEdgesNode"]


class QueryNotificationsNotificationsEdgesNode(BaseModel):
    id: str
    asset_id: str = Field(alias="assetId")
    asset_name: str = Field(alias="assetName")
    created_at: str = Field(alias="createdAt")
    description: str
    entry: Optional[
        Annotated[
            Union[
                "QueryNotificationsNotificationsEdgesNodeEntryCveNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryComponentNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryBinaryProtectionsNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryCertificateNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryCredentialUserNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryCredentialHashNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryPrivateKeyNotificationEntry",
                "QueryNotificationsNotificationsEdgesNodeEntryEmptyNotificationEntry",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    is_unread: bool = Field(alias="isUnread")
    parser: NotificationParser
    title: str
    type: NotificationType
    user: Optional[str]


class QueryNotificationsNotificationsEdgesNodeEntryCveNotificationEntry(BaseModel):
    typename__: Literal["CveNotificationEntry"] = Field(alias="__typename")
    cve_id: str = Field(alias="cveId")


class QueryNotificationsNotificationsEdgesNodeEntryComponentNotificationEntry(
    BaseModel
):
    typename__: Literal["ComponentNotificationEntry"] = Field(alias="__typename")
    component_name: str = Field(alias="componentName")
    component_version: str = Field(alias="componentVersion")
    vendor: Optional[str]


class QueryNotificationsNotificationsEdgesNodeEntryBinaryProtectionsNotificationEntry(
    BaseModel
):
    typename__: Literal["BinaryProtectionsNotificationEntry"] = Field(
        alias="__typename"
    )
    file_path: str = Field(alias="filePath")


class QueryNotificationsNotificationsEdgesNodeEntryCertificateNotificationEntry(
    BaseModel
):
    typename__: Literal["CertificateNotificationEntry"] = Field(alias="__typename")
    file_path: str = Field(alias="filePath")
    sha_256_thumbprint: str = Field(alias="sha256Thumbprint")


class QueryNotificationsNotificationsEdgesNodeEntryCredentialUserNotificationEntry(
    BaseModel
):
    typename__: Literal["CredentialUserNotificationEntry"] = Field(alias="__typename")
    file_path: str = Field(alias="filePath")
    username: str


class QueryNotificationsNotificationsEdgesNodeEntryCredentialHashNotificationEntry(
    BaseModel
):
    typename__: Literal["CredentialHashNotificationEntry"] = Field(alias="__typename")
    file_path: str = Field(alias="filePath")
    hash: str


class QueryNotificationsNotificationsEdgesNodeEntryPrivateKeyNotificationEntry(
    BaseModel
):
    typename__: Literal["PrivateKeyNotificationEntry"] = Field(alias="__typename")
    file_path: str = Field(alias="filePath")
    match_hash: str = Field(alias="matchHash")


class QueryNotificationsNotificationsEdgesNodeEntryEmptyNotificationEntry(BaseModel):
    typename__: Literal["EmptyNotificationEntry"] = Field(alias="__typename")
    empty: Optional[bool] = Field(alias="_empty")


class QueryNotificationsNotificationsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryNotifications.model_rebuild()
QueryNotificationsNotifications.model_rebuild()
QueryNotificationsNotificationsEdges.model_rebuild()
QueryNotificationsNotificationsEdgesNode.model_rebuild()
