# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectVersions(BaseModel):
    jira_project_versions: list["QueryJiraProjectVersionsJiraProjectVersions"] = Field(
        alias="jiraProjectVersions"
    )


class QueryJiraProjectVersionsJiraProjectVersions(BaseModel):
    id: str
    archived: bool
    description: Optional[str]
    name: str
    release_date: Optional[str] = Field(alias="releaseDate")
    released: bool


QueryJiraProjectVersions.model_rebuild()
