# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectSprints(BaseModel):
    jira_project_sprints: list["QueryJiraProjectSprintsJiraProjectSprints"] = Field(
        alias="jiraProjectSprints"
    )


class QueryJiraProjectSprintsJiraProjectSprints(BaseModel):
    id: str
    board_id: Optional[str] = Field(alias="boardId")
    end_date: Optional[str] = Field(alias="endDate")
    name: str
    start_date: Optional[str] = Field(alias="startDate")
    state: str


QueryJiraProjectSprints.model_rebuild()
