# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EvidenceEdgeType, EvidenceEntryType


class QueryGetSecretReachability(BaseModel):
    get_secret_reachability: Optional[
        list["QueryGetSecretReachabilityGetSecretReachability"]
    ] = Field(alias="getSecretReachability")


class QueryGetSecretReachabilityGetSecretReachability(BaseModel):
    cve_id: Optional[str] = Field(alias="cveId")
    entry_point: Optional[str] = Field(alias="entryPoint")
    entry_type: Optional[EvidenceEntryType] = Field(alias="entryType")
    scripts: Optional[
        list[Optional["QueryGetSecretReachabilityGetSecretReachabilityScripts"]]
    ]
    user: Optional[str]


class QueryGetSecretReachabilityGetSecretReachabilityScripts(BaseModel):
    detail: Optional[str]
    edge_type: Optional[EvidenceEdgeType] = Field(alias="edgeType")
    invocation: Optional[str]
    path: Optional[str]


QueryGetSecretReachability.model_rebuild()
QueryGetSecretReachabilityGetSecretReachability.model_rebuild()
