# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from datetime import datetime
from typing import Annotated, Any, Optional

from pydantic import BeforeValidator, Field

from .base_model import BaseModel
from .custom_scalars import parse_datetime
from .enums import LicenseIssueSeverity, LicenseIssueStatus


class QueryLicenseIssue(BaseModel):
    license_issue: Optional["QueryLicenseIssueLicenseIssue"] = Field(
        alias="licenseIssue"
    )


class QueryLicenseIssueLicenseIssue(BaseModel):
    component_id: Optional[str] = Field(alias="componentId")
    component_name: Optional[str] = Field(alias="componentName")
    component_version: Optional[str] = Field(alias="componentVersion")
    evidence: Optional["QueryLicenseIssueLicenseIssueEvidence"]
    issue_description: Optional[str] = Field(alias="issueDescription")
    issue_id: str = Field(alias="issueId")
    issue_name: str = Field(alias="issueName")
    last_modified: Optional[Annotated[datetime, BeforeValidator(parse_datetime)]] = (
        Field(alias="lastModified")
    )
    license: Optional["QueryLicenseIssueLicenseIssueLicense"]
    potential_solution: Optional[str] = Field(alias="potentialSolution")
    remediation: Optional["QueryLicenseIssueLicenseIssueRemediation"]
    severity: Optional[LicenseIssueSeverity]
    status: LicenseIssueStatus


class QueryLicenseIssueLicenseIssueEvidence(BaseModel):
    children: Optional[Any]
    component_id: Optional[str] = Field(alias="componentId")
    license_name: Optional[str] = Field(alias="licenseName")
    name: Optional[str]
    package_type: Optional[str] = Field(alias="packageType")
    spdx_id: Optional[str] = Field(alias="spdxId")
    vendor: Optional[str]
    version: Optional[str]


class QueryLicenseIssueLicenseIssueLicense(BaseModel):
    additional_counts: Optional[
        "QueryLicenseIssueLicenseIssueLicenseAdditionalCounts"
    ] = Field(alias="additionalCounts")
    additional_info_urls_list: Optional[list[Optional[str]]] = Field(
        alias="additionalInfoUrlsList"
    )
    license_name: Optional[str] = Field(alias="licenseName")
    license_notes: Optional[str] = Field(alias="licenseNotes")
    license_type: Optional[str] = Field(alias="licenseType")
    license_url: Optional[str] = Field(alias="licenseUrl")
    spdx_id: Optional[str] = Field(alias="spdxId")
    url: Optional[str]


class QueryLicenseIssueLicenseIssueLicenseAdditionalCounts(BaseModel):
    associated_components: Optional[int] = Field(alias="associatedComponents")
    issues: Optional[int]


class QueryLicenseIssueLicenseIssueRemediation(BaseModel):
    created_time: Optional[Annotated[datetime, BeforeValidator(parse_datetime)]] = (
        Field(alias="createdTime")
    )
    detail: Optional[str]
    user: Optional[str]


QueryLicenseIssue.model_rebuild()
QueryLicenseIssueLicenseIssue.model_rebuild()
QueryLicenseIssueLicenseIssueLicense.model_rebuild()
