# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryLicensesSpdxIds(BaseModel):
    licenses_spdx_ids: Optional[list[Optional[str]]] = Field(alias="licensesSpdxIds")
