# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import RiseAIStatus


class QueryRiseAIAvailability(BaseModel):
    rise_ai_availability: "QueryRiseAIAvailabilityRiseAiAvailability" = Field(
        alias="riseAIAvailability"
    )


class QueryRiseAIAvailabilityRiseAiAvailability(BaseModel):
    available: Optional[bool]
    eligible: Optional[bool]
    status: Optional[RiseAIStatus]


QueryRiseAIAvailability.model_rebuild()
