# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectComponents(BaseModel):
    jira_project_components: list["QueryJiraProjectComponentsJiraProjectComponents"] = (
        Field(alias="jiraProjectComponents")
    )


class QueryJiraProjectComponentsJiraProjectComponents(BaseModel):
    id: str
    description: Optional[str]
    name: str


QueryJiraProjectComponents.model_rebuild()
