# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGetSecurityGroupDeleteImpact(BaseModel):
    get_security_group_delete_impact: (
        "QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpact"
    ) = Field(alias="getSecurityGroupDeleteImpact")


class QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpact(BaseModel):
    total_members: int = Field(alias="totalMembers")
    users_who_lose_all: list[
        "QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpactUsersWhoLoseAll"
    ] = Field(alias="usersWhoLoseAll")
    users_who_retain: list[
        "QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpactUsersWhoRetain"
    ] = Field(alias="usersWhoRetain")


class QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpactUsersWhoLoseAll(
    BaseModel
):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


class QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpactUsersWhoRetain(
    BaseModel
):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


QueryGetSecurityGroupDeleteImpact.model_rebuild()
QueryGetSecurityGroupDeleteImpactGetSecurityGroupDeleteImpact.model_rebuild()
