# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraSpaceIssueTypes(BaseModel):
    jira_space_issue_types: list["QueryJiraSpaceIssueTypesJiraSpaceIssueTypes"] = Field(
        alias="jiraSpaceIssueTypes"
    )


class QueryJiraSpaceIssueTypesJiraSpaceIssueTypes(BaseModel):
    id: str
    icon_url: Optional[str] = Field(alias="iconUrl")
    name: str
    subtask: bool


QueryJiraSpaceIssueTypes.model_rebuild()
