# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    RiskCategory,
    SecretCategory,
    SecretRemediationStatus,
    SecretSeverity,
    SecretType,
)


class QuerySecrets(BaseModel):
    secrets: Optional["QuerySecretsSecrets"]


class QuerySecretsSecrets(BaseModel):
    edges: Optional[list["QuerySecretsSecretsEdges"]]
    page_info: "QuerySecretsSecretsPageInfo" = Field(alias="pageInfo")


class QuerySecretsSecretsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QuerySecretsSecretsEdgesNode"]


class QuerySecretsSecretsEdgesNode(BaseModel):
    id: str
    category: SecretCategory
    category_label: Optional[str] = Field(alias="categoryLabel")
    correlations: Optional[list["QuerySecretsSecretsEdgesNodeCorrelations"]]
    correlations_count: int = Field(alias="correlationsCount")
    current_remediation: Optional["QuerySecretsSecretsEdgesNodeCurrentRemediation"] = (
        Field(alias="currentRemediation")
    )
    description: Optional[str]
    file_path: Optional[str] = Field(alias="filePath")
    raw_secret: Optional[str] = Field(alias="rawSecret")
    remediation_status: Optional[SecretRemediationStatus] = Field(
        alias="remediationStatus"
    )
    sanitized_secret: Optional[str] = Field(alias="sanitizedSecret")
    severity: SecretSeverity
    subtype: Optional[str]
    type: Optional[SecretType]


class QuerySecretsSecretsEdgesNodeCorrelations(BaseModel):
    artifact: Optional[str]
    asset_id: Optional[str] = Field(alias="assetId")
    asset_name: Optional[str] = Field(alias="assetName")
    location: Optional[str]
    risk: Optional["QuerySecretsSecretsEdgesNodeCorrelationsRisk"]
    updated_at: Optional[str] = Field(alias="updatedAt")


class QuerySecretsSecretsEdgesNodeCorrelationsRisk(BaseModel):
    category: Optional[RiskCategory]
    raw_score: Optional[float] = Field(alias="rawScore")
    score: Optional[float]


class QuerySecretsSecretsEdgesNodeCurrentRemediation(BaseModel):
    author: Optional[str]
    created_at: Optional[str] = Field(alias="createdAt")
    description: Optional[str]
    secret_id: Optional[str] = Field(alias="secretId")
    status: Optional[SecretRemediationStatus]


class QuerySecretsSecretsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QuerySecrets.model_rebuild()
QuerySecretsSecrets.model_rebuild()
QuerySecretsSecretsEdges.model_rebuild()
QuerySecretsSecretsEdgesNode.model_rebuild()
QuerySecretsSecretsEdgesNodeCorrelations.model_rebuild()
