# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGetRoleDeleteImpact(BaseModel):
    get_role_delete_impact: "QueryGetRoleDeleteImpactGetRoleDeleteImpact" = Field(
        alias="getRoleDeleteImpact"
    )


class QueryGetRoleDeleteImpactGetRoleDeleteImpact(BaseModel):
    acr_count: int = Field(alias="acrCount")
    total_affected_users: int = Field(alias="totalAffectedUsers")
    users_who_lose_all: list[
        "QueryGetRoleDeleteImpactGetRoleDeleteImpactUsersWhoLoseAll"
    ] = Field(alias="usersWhoLoseAll")
    users_who_retain: list[
        "QueryGetRoleDeleteImpactGetRoleDeleteImpactUsersWhoRetain"
    ] = Field(alias="usersWhoRetain")


class QueryGetRoleDeleteImpactGetRoleDeleteImpactUsersWhoLoseAll(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


class QueryGetRoleDeleteImpactGetRoleDeleteImpactUsersWhoRetain(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


QueryGetRoleDeleteImpact.model_rebuild()
QueryGetRoleDeleteImpactGetRoleDeleteImpact.model_rebuild()
