# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectLabels(BaseModel):
    jira_project_labels: list["QueryJiraProjectLabelsJiraProjectLabels"] = Field(
        alias="jiraProjectLabels"
    )


class QueryJiraProjectLabelsJiraProjectLabels(BaseModel):
    name: str


QueryJiraProjectLabels.model_rebuild()
