# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EvidenceEdgeType, EvidenceEntryType


class QueryGetDependencyReachability(BaseModel):
    get_dependency_reachability: Optional[
        list["QueryGetDependencyReachabilityGetDependencyReachability"]
    ] = Field(alias="getDependencyReachability")


class QueryGetDependencyReachabilityGetDependencyReachability(BaseModel):
    cve_id: Optional[str] = Field(alias="cveId")
    entry_point: Optional[str] = Field(alias="entryPoint")
    entry_type: Optional[EvidenceEntryType] = Field(alias="entryType")
    scripts: Optional[
        list[Optional["QueryGetDependencyReachabilityGetDependencyReachabilityScripts"]]
    ]
    user: Optional[str]


class QueryGetDependencyReachabilityGetDependencyReachabilityScripts(BaseModel):
    detail: Optional[str]
    edge_type: Optional[EvidenceEdgeType] = Field(alias="edgeType")
    invocation: Optional[str]
    path: Optional[str]


QueryGetDependencyReachability.model_rebuild()
QueryGetDependencyReachabilityGetDependencyReachability.model_rebuild()
