# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecurityGroupMemberSource


class QueryListSecurityGroupMembers(BaseModel):
    list_security_group_members: (
        "QueryListSecurityGroupMembersListSecurityGroupMembers"
    ) = Field(alias="listSecurityGroupMembers")


class QueryListSecurityGroupMembersListSecurityGroupMembers(BaseModel):
    edges: Optional[
        list[Optional["QueryListSecurityGroupMembersListSecurityGroupMembersEdges"]]
    ]
    page_info: "QueryListSecurityGroupMembersListSecurityGroupMembersPageInfo" = Field(
        alias="pageInfo"
    )


class QueryListSecurityGroupMembersListSecurityGroupMembersEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListSecurityGroupMembersListSecurityGroupMembersEdgesNode"]


class QueryListSecurityGroupMembersListSecurityGroupMembersEdgesNode(BaseModel):
    accessible_asset_count: Optional[int] = Field(alias="accessibleAssetCount")
    created_time: Optional[str] = Field(alias="createdTime")
    display_name: Optional[str] = Field(alias="displayName")
    email: Optional[str]
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    source: SecurityGroupMemberSource
    user_id: Optional[str] = Field(alias="userId")


class QueryListSecurityGroupMembersListSecurityGroupMembersPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListSecurityGroupMembers.model_rebuild()
QueryListSecurityGroupMembersListSecurityGroupMembers.model_rebuild()
QueryListSecurityGroupMembersListSecurityGroupMembersEdges.model_rebuild()
