# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    MisconfigurationCategoryType,
    MisconfigurationSeverityType,
    MisconfigurationStatusType,
)
from .fragments import PageInfoFields


class QueryMisconfigurationsLite(BaseModel):
    misconfigurations: Optional["QueryMisconfigurationsLiteMisconfigurations"]


class QueryMisconfigurationsLiteMisconfigurations(BaseModel):
    edges: Optional[list[Optional["QueryMisconfigurationsLiteMisconfigurationsEdges"]]]
    page_info: Optional["QueryMisconfigurationsLiteMisconfigurationsPageInfo"] = Field(
        alias="pageInfo"
    )


class QueryMisconfigurationsLiteMisconfigurationsEdges(BaseModel):
    cursor: str
    node: Optional["QueryMisconfigurationsLiteMisconfigurationsEdgesNode"]


class QueryMisconfigurationsLiteMisconfigurationsEdgesNode(BaseModel):
    check_id: Optional[str] = Field(alias="checkId")
    display_name: Optional[str] = Field(alias="displayName")
    category: Optional[MisconfigurationCategoryType]
    severity: Optional[MisconfigurationSeverityType]
    result: Optional[MisconfigurationStatusType]
    correlations_count: Optional[int] = Field(alias="correlationsCount")


class QueryMisconfigurationsLiteMisconfigurationsPageInfo(PageInfoFields):
    pass


QueryMisconfigurationsLite.model_rebuild()
QueryMisconfigurationsLiteMisconfigurations.model_rebuild()
QueryMisconfigurationsLiteMisconfigurationsEdges.model_rebuild()
