# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from datetime import datetime
from typing import Annotated

from pydantic import BeforeValidator, Field

from .base_model import BaseModel
from .custom_scalars import parse_datetime


class QueryOrgLevelInformation(BaseModel):
    org_level_information: "QueryOrgLevelInformationOrgLevelInformation" = Field(
        alias="orgLevelInformation"
    )


class QueryOrgLevelInformationOrgLevelInformation(BaseModel):
    last_updated_at: Annotated[datetime, BeforeValidator(parse_datetime)] = Field(
        alias="lastUpdatedAt"
    )


QueryOrgLevelInformation.model_rebuild()
