# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryLicenseIssuesExternalFilters(BaseModel):
    license_issues_external_filters: (
        "QueryLicenseIssuesExternalFiltersLicenseIssuesExternalFilters"
    ) = Field(alias="licenseIssuesExternalFilters")


class QueryLicenseIssuesExternalFiltersLicenseIssuesExternalFilters(BaseModel):
    blocker: int
    in_review: int = Field(alias="inReview")
    major: int
    minor: int
    resolved: int
    types: Optional[
        list[
            Optional[
                "QueryLicenseIssuesExternalFiltersLicenseIssuesExternalFiltersTypes"
            ]
        ]
    ]
    unreviewed: int


class QueryLicenseIssuesExternalFiltersLicenseIssuesExternalFiltersTypes(BaseModel):
    count: Optional[int]
    type: Optional[str]


QueryLicenseIssuesExternalFilters.model_rebuild()
QueryLicenseIssuesExternalFiltersLicenseIssuesExternalFilters.model_rebuild()
