# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from pydantic import Field

from .base_model import BaseModel


class QueryListPermissions(BaseModel):
    list_permissions: "QueryListPermissionsListPermissions" = Field(
        alias="listPermissions"
    )


class QueryListPermissionsListPermissions(BaseModel):
    permissions: list["QueryListPermissionsListPermissionsPermissions"]


class QueryListPermissionsListPermissionsPermissions(BaseModel):
    id: str
    category: str
    description: str


QueryListPermissions.model_rebuild()
QueryListPermissionsListPermissions.model_rebuild()
