# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListMySecurityGroups(BaseModel):
    list_my_security_groups: "QueryListMySecurityGroupsListMySecurityGroups" = Field(
        alias="listMySecurityGroups"
    )


class QueryListMySecurityGroupsListMySecurityGroups(BaseModel):
    edges: Optional[
        list[Optional["QueryListMySecurityGroupsListMySecurityGroupsEdges"]]
    ]
    page_info: "QueryListMySecurityGroupsListMySecurityGroupsPageInfo" = Field(
        alias="pageInfo"
    )


class QueryListMySecurityGroupsListMySecurityGroupsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListMySecurityGroupsListMySecurityGroupsEdgesNode"]


class QueryListMySecurityGroupsListMySecurityGroupsEdgesNode(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    description: Optional[str]
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    member_count: Optional[int] = Field(alias="memberCount")
    members: list["QueryListMySecurityGroupsListMySecurityGroupsEdgesNodeMembers"]
    name: str


class QueryListMySecurityGroupsListMySecurityGroupsEdgesNodeMembers(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


class QueryListMySecurityGroupsListMySecurityGroupsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListMySecurityGroups.model_rebuild()
QueryListMySecurityGroupsListMySecurityGroups.model_rebuild()
QueryListMySecurityGroupsListMySecurityGroupsEdges.model_rebuild()
QueryListMySecurityGroupsListMySecurityGroupsEdgesNode.model_rebuild()
