# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListSecurityGroups(BaseModel):
    list_security_groups: "QueryListSecurityGroupsListSecurityGroups" = Field(
        alias="listSecurityGroups"
    )


class QueryListSecurityGroupsListSecurityGroups(BaseModel):
    edges: Optional[list[Optional["QueryListSecurityGroupsListSecurityGroupsEdges"]]]
    page_info: "QueryListSecurityGroupsListSecurityGroupsPageInfo" = Field(
        alias="pageInfo"
    )


class QueryListSecurityGroupsListSecurityGroupsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListSecurityGroupsListSecurityGroupsEdgesNode"]


class QueryListSecurityGroupsListSecurityGroupsEdgesNode(BaseModel):
    id: str
    created_by: Optional[str] = Field(alias="createdBy")
    created_time: Optional[str] = Field(alias="createdTime")
    description: Optional[str]
    last_modified_time: Optional[str] = Field(alias="lastModifiedTime")
    last_seen_time: Optional[str] = Field(alias="lastSeenTime")
    member_count: Optional[int] = Field(alias="memberCount")
    members: list["QueryListSecurityGroupsListSecurityGroupsEdgesNodeMembers"]
    name: str


class QueryListSecurityGroupsListSecurityGroupsEdgesNodeMembers(BaseModel):
    display_name: Optional[str] = Field(alias="displayName")
    email: str
    user_id: str = Field(alias="userId")


class QueryListSecurityGroupsListSecurityGroupsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListSecurityGroups.model_rebuild()
QueryListSecurityGroupsListSecurityGroups.model_rebuild()
QueryListSecurityGroupsListSecurityGroupsEdges.model_rebuild()
QueryListSecurityGroupsListSecurityGroupsEdgesNode.model_rebuild()
