# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGetAiModelData(BaseModel):
    get_ai_model_data: Optional["QueryGetAiModelDataGetAiModelData"] = Field(
        alias="getAiModelData"
    )


class QueryGetAiModelDataGetAiModelData(BaseModel):
    ai_model_data: Optional["QueryGetAiModelDataGetAiModelDataAiModelData"] = Field(
        alias="aiModelData"
    )


class QueryGetAiModelDataGetAiModelDataAiModelData(BaseModel):
    ai_model_architecture_type: Optional[str] = Field(alias="aiModelArchitectureType")
    author: Optional[str]
    description: Optional[str]
    license: Optional[str]
    name: Optional[str]
    organization: Optional[str]
    version: Optional[str]


QueryGetAiModelData.model_rebuild()
QueryGetAiModelDataGetAiModelData.model_rebuild()
