# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ActivityEntityType,
    NotificationActivityKind,
    NotificationActivityThresholdField,
    NotificationActivityThresholdOperator,
    NotificationConfigurationChannel,
    NotificationConfigurationType,
)


class QueryListNotificationConfigurations(BaseModel):
    list_notification_configurations: (
        "QueryListNotificationConfigurationsListNotificationConfigurations"
    ) = Field(alias="listNotificationConfigurations")


class QueryListNotificationConfigurationsListNotificationConfigurations(BaseModel):
    edges: Optional[
        list[
            Optional[
                "QueryListNotificationConfigurationsListNotificationConfigurationsEdges"
            ]
        ]
    ]
    page_info: (
        "QueryListNotificationConfigurationsListNotificationConfigurationsPageInfo"
    ) = Field(alias="pageInfo")


class QueryListNotificationConfigurationsListNotificationConfigurationsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional[
        "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNode"
    ]


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNode(
    BaseModel
):
    id: Optional[str]
    activity_scopes: list[
        "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeActivityScopes"
    ] = Field(alias="activityScopes")
    channel: Optional[NotificationConfigurationChannel]
    channel_configuration: Optional[
        Annotated[
            Union[
                "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationWebhook",
                "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationEmail",
                "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationApplication",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="channelConfiguration")
    created_at: Optional[str] = Field(alias="createdAt")
    disabled: Optional[bool]
    inventory_scopes: list[
        "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeInventoryScopes"
    ] = Field(alias="inventoryScopes")
    name: Optional[str]
    silenced: Optional[bool]
    type: Optional[NotificationConfigurationType]
    updated_at: Optional[str] = Field(alias="updatedAt")
    updated_by: Optional[str] = Field(alias="updatedBy")


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeActivityScopes(
    BaseModel
):
    activity_type: Optional[NotificationActivityKind] = Field(alias="activityType")
    entity_type: Optional[ActivityEntityType] = Field(alias="entityType")
    threshold: Optional[
        "QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeActivityScopesThreshold"
    ]


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeActivityScopesThreshold(
    BaseModel
):
    key: NotificationActivityThresholdField
    operator: NotificationActivityThresholdOperator
    value: str


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationWebhook(
    BaseModel
):
    typename__: Literal["NotificationConfigurationWebhook"] = Field(alias="__typename")
    url: str


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationEmail(
    BaseModel
):
    typename__: Literal["NotificationConfigurationEmail"] = Field(alias="__typename")
    address: str


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeChannelConfigurationNotificationConfigurationApplication(
    BaseModel
):
    typename__: Literal["NotificationConfigurationApplication"] = Field(
        alias="__typename"
    )
    empty: Optional[bool] = Field(alias="_empty")


class QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeInventoryScopes(
    BaseModel
):
    asset_id: Optional[str] = Field(alias="assetId")
    group_id: Optional[str] = Field(alias="groupId")
    organization: Optional[bool]


class QueryListNotificationConfigurationsListNotificationConfigurationsPageInfo(
    BaseModel
):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListNotificationConfigurations.model_rebuild()
QueryListNotificationConfigurationsListNotificationConfigurations.model_rebuild()
QueryListNotificationConfigurationsListNotificationConfigurationsEdges.model_rebuild()
QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNode.model_rebuild()
QueryListNotificationConfigurationsListNotificationConfigurationsEdgesNodeActivityScopes.model_rebuild()
