# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGetMyPermissions(BaseModel):
    get_my_permissions: "QueryGetMyPermissionsGetMyPermissions" = Field(
        alias="getMyPermissions"
    )


class QueryGetMyPermissionsGetMyPermissions(BaseModel):
    highest_precedence_role: Optional[str] = Field(alias="highestPrecedenceRole")
    permissions: list[str]
    roles: list["QueryGetMyPermissionsGetMyPermissionsRoles"]


class QueryGetMyPermissionsGetMyPermissionsRoles(BaseModel):
    at_asset: bool = Field(alias="atAsset")
    at_asset_group: bool = Field(alias="atAssetGroup")
    at_org: bool = Field(alias="atOrg")
    role_name: str = Field(alias="roleName")


QueryGetMyPermissions.model_rebuild()
QueryGetMyPermissionsGetMyPermissions.model_rebuild()
