# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import NotificationLogStatus


class QueryListNotificationLogs(BaseModel):
    list_notification_logs: "QueryListNotificationLogsListNotificationLogs" = Field(
        alias="listNotificationLogs"
    )


class QueryListNotificationLogsListNotificationLogs(BaseModel):
    edges: Optional[
        list[Optional["QueryListNotificationLogsListNotificationLogsEdges"]]
    ]
    page_info: "QueryListNotificationLogsListNotificationLogsPageInfo" = Field(
        alias="pageInfo"
    )


class QueryListNotificationLogsListNotificationLogsEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryListNotificationLogsListNotificationLogsEdgesNode"]


class QueryListNotificationLogsListNotificationLogsEdgesNode(BaseModel):
    event_count: Optional[int] = Field(alias="eventCount")
    messages: Optional[list[str]]
    notification_configuration_id: Optional[str] = Field(
        alias="notificationConfigurationId"
    )
    status: Optional[NotificationLogStatus]
    timestamp: Optional[str]


class QueryListNotificationLogsListNotificationLogsPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListNotificationLogs.model_rebuild()
QueryListNotificationLogsListNotificationLogs.model_rebuild()
QueryListNotificationLogsListNotificationLogsEdges.model_rebuild()
