# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryListAssetCryptoLibraries(BaseModel):
    list_asset_crypto_libraries: Optional[
        "QueryListAssetCryptoLibrariesListAssetCryptoLibraries"
    ] = Field(alias="listAssetCryptoLibraries")


class QueryListAssetCryptoLibrariesListAssetCryptoLibraries(BaseModel):
    edges: Optional[
        list[Optional["QueryListAssetCryptoLibrariesListAssetCryptoLibrariesEdges"]]
    ]
    page_info: Optional[
        "QueryListAssetCryptoLibrariesListAssetCryptoLibrariesPageInfo"
    ] = Field(alias="pageInfo")


class QueryListAssetCryptoLibrariesListAssetCryptoLibrariesEdges(BaseModel):
    cursor: str
    node: Optional["QueryListAssetCryptoLibrariesListAssetCryptoLibrariesEdgesNode"]


class QueryListAssetCryptoLibrariesListAssetCryptoLibrariesEdgesNode(BaseModel):
    fips: Optional[str]
    name: Optional[str]
    pqc_ready: Optional[bool] = Field(alias="pqcReady")
    purl: Optional[str]
    vendor: Optional[str]
    version: Optional[str]


class QueryListAssetCryptoLibrariesListAssetCryptoLibrariesPageInfo(BaseModel):
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    total_count: Optional[int] = Field(alias="totalCount")


QueryListAssetCryptoLibraries.model_rebuild()
QueryListAssetCryptoLibrariesListAssetCryptoLibraries.model_rebuild()
QueryListAssetCryptoLibrariesListAssetCryptoLibrariesEdges.model_rebuild()
