# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFields


class QueryVulnerabilitiesLite(BaseModel):
    vulnerabilities: Optional["QueryVulnerabilitiesLiteVulnerabilities"]


class QueryVulnerabilitiesLiteVulnerabilities(BaseModel):
    edges: Optional[list[Optional["QueryVulnerabilitiesLiteVulnerabilitiesEdges"]]]
    page_info: "QueryVulnerabilitiesLiteVulnerabilitiesPageInfo" = Field(
        alias="pageInfo"
    )


class QueryVulnerabilitiesLiteVulnerabilitiesEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryVulnerabilitiesLiteVulnerabilitiesEdgesNode"]


class QueryVulnerabilitiesLiteVulnerabilitiesEdgesNode(BaseModel):
    id: str
    cve: Optional[str]
    name: Optional[str]
    severity: Optional[str]
    cvss_score: Optional[float] = Field(alias="cvssScore")
    epss_score: Optional[float] = Field(alias="epssScore")
    epss_percentile: Optional[float] = Field(alias="epssPercentile")
    fix_versions: Optional[list[Optional[str]]] = Field(alias="fixVersions")
    identification_ids: Optional[list[Optional[str]]] = Field(alias="identificationIds")
    in_known_exploited_vulnerabilities: Optional[bool] = Field(
        alias="inKnownExploitedVulnerabilities"
    )
    is_reachable: Optional[bool] = Field(alias="isReachable")
    correlations_count: Optional[int] = Field(alias="correlationsCount")


class QueryVulnerabilitiesLiteVulnerabilitiesPageInfo(PageInfoFields):
    pass


QueryVulnerabilitiesLite.model_rebuild()
QueryVulnerabilitiesLiteVulnerabilities.model_rebuild()
QueryVulnerabilitiesLiteVulnerabilitiesEdges.model_rebuild()
