# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryLicense(BaseModel):
    license: Optional["QueryLicenseLicense"]


class QueryLicenseLicense(BaseModel):
    additional_counts: Optional["QueryLicenseLicenseAdditionalCounts"] = Field(
        alias="additionalCounts"
    )
    additional_info_urls_list: Optional[list[Optional[str]]] = Field(
        alias="additionalInfoUrlsList"
    )
    license_name: Optional[str] = Field(alias="licenseName")
    license_notes: Optional[str] = Field(alias="licenseNotes")
    license_type: Optional[str] = Field(alias="licenseType")
    license_url: Optional[str] = Field(alias="licenseUrl")
    spdx_id: Optional[str] = Field(alias="spdxId")
    url: Optional[str]


class QueryLicenseLicenseAdditionalCounts(BaseModel):
    associated_components: Optional[int] = Field(alias="associatedComponents")
    issues: Optional[int]


QueryLicense.model_rebuild()
QueryLicenseLicense.model_rebuild()
