# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryIdentifiedComponentsPreview(BaseModel):
    identified_components_preview: Optional[
        "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreview"
    ] = Field(alias="identifiedComponentsPreview")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreview(BaseModel):
    application: (
        "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewApplication"
    )
    container: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewContainer"
    device: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewDevice"
    framework: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewFramework"
    kernel: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewKernel"
    kernel_module: (
        "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewKernelModule"
    ) = Field(alias="kernelModule")
    library: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewLibrary"
    os: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewOs"
    package: "QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewPackage"


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewApplication(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewContainer(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewDevice(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewFramework(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewKernel(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewKernelModule(
    BaseModel
):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewLibrary(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewOs(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


class QueryIdentifiedComponentsPreviewIdentifiedComponentsPreviewPackage(BaseModel):
    after_count: Optional[int] = Field(alias="afterCount")
    before_count: Optional[int] = Field(alias="beforeCount")


QueryIdentifiedComponentsPreview.model_rebuild()
QueryIdentifiedComponentsPreviewIdentifiedComponentsPreview.model_rebuild()
