# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecretRemediationStatus


class QuerySecretStatusCount(BaseModel):
    secret_status_count: Optional[
        list[Optional["QuerySecretStatusCountSecretStatusCount"]]
    ] = Field(alias="secretStatusCount")


class QuerySecretStatusCountSecretStatusCount(BaseModel):
    count: Optional[int]
    name: Optional[SecretRemediationStatus]


QuerySecretStatusCount.model_rebuild()
