# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraProjectUsers(BaseModel):
    jira_project_users: list["QueryJiraProjectUsersJiraProjectUsers"] = Field(
        alias="jiraProjectUsers"
    )


class QueryJiraProjectUsersJiraProjectUsers(BaseModel):
    account_id: str = Field(alias="accountId")
    active: bool
    avatar_url: Optional[str] = Field(alias="avatarUrl")
    display_name: str = Field(alias="displayName")
    email_address: Optional[str] = Field(alias="emailAddress")


QueryJiraProjectUsers.model_rebuild()
