# Generated by ariadne-codegen
# Source: ../sdk-artifacts/synthetic_operations.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SecretType


class QuerySecretTypesAndCount(BaseModel):
    secret_types_and_count: Optional["QuerySecretTypesAndCountSecretTypesAndCount"] = (
        Field(alias="secretTypesAndCount")
    )


class QuerySecretTypesAndCountSecretTypesAndCount(BaseModel):
    total_types: Optional[int] = Field(alias="totalTypes")
    type_counts: Optional[
        list[Optional["QuerySecretTypesAndCountSecretTypesAndCountTypeCounts"]]
    ] = Field(alias="typeCounts")


class QuerySecretTypesAndCountSecretTypesAndCountTypeCounts(BaseModel):
    count: Optional[int]
    type: Optional[SecretType]


QuerySecretTypesAndCount.model_rebuild()
QuerySecretTypesAndCountSecretTypesAndCount.model_rebuild()
