# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import AssetAnalyticLite, PageInfoFields


class QueryAssetsRelaySummary(BaseModel):
    assets_relay: Optional["QueryAssetsRelaySummaryAssetsRelay"] = Field(
        alias="assetsRelay"
    )


class QueryAssetsRelaySummaryAssetsRelay(BaseModel):
    edges: Optional[list[Optional["QueryAssetsRelaySummaryAssetsRelayEdges"]]]
    page_info: "QueryAssetsRelaySummaryAssetsRelayPageInfo" = Field(alias="pageInfo")


class QueryAssetsRelaySummaryAssetsRelayEdges(BaseModel):
    cursor: Optional[str]
    node: Optional["QueryAssetsRelaySummaryAssetsRelayEdgesNode"]


class QueryAssetsRelaySummaryAssetsRelayEdgesNode(BaseModel):
    id: Optional[str]
    name: Optional[str]
    analytic: Optional["QueryAssetsRelaySummaryAssetsRelayEdgesNodeAnalytic"]


class QueryAssetsRelaySummaryAssetsRelayEdgesNodeAnalytic(AssetAnalyticLite):
    pass


class QueryAssetsRelaySummaryAssetsRelayPageInfo(PageInfoFields):
    pass


QueryAssetsRelaySummary.model_rebuild()
QueryAssetsRelaySummaryAssetsRelay.model_rebuild()
QueryAssetsRelaySummaryAssetsRelayEdges.model_rebuild()
QueryAssetsRelaySummaryAssetsRelayEdgesNode.model_rebuild()
