# Generated by ariadne-codegen
# Source: ../sdk-artifacts/queries/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraStatusMappingProblems(BaseModel):
    jira_status_mapping_problems: list[
        "QueryJiraStatusMappingProblemsJiraStatusMappingProblems"
    ] = Field(alias="jiraStatusMappingProblems")


class QueryJiraStatusMappingProblemsJiraStatusMappingProblems(BaseModel):
    jira_space_id: str = Field(alias="jiraSpaceId")
    mapping_problems: list[
        "QueryJiraStatusMappingProblemsJiraStatusMappingProblemsMappingProblems"
    ] = Field(alias="mappingProblems")
    project_key: str = Field(alias="projectKey")
    project_name: str = Field(alias="projectName")
    space_problems: list[
        "QueryJiraStatusMappingProblemsJiraStatusMappingProblemsSpaceProblems"
    ] = Field(alias="spaceProblems")


class QueryJiraStatusMappingProblemsJiraStatusMappingProblemsMappingProblems(BaseModel):
    code: str
    detail: Optional[str]
    detected_at: Optional[str] = Field(alias="detectedAt")
    jira_issue_type_id: Optional[str] = Field(alias="jiraIssueTypeId")
    jira_issue_type_name: Optional[str] = Field(alias="jiraIssueTypeName")
    jira_issue_type_subtask: bool = Field(alias="jiraIssueTypeSubtask")
    jira_status_id: Optional[str] = Field(alias="jiraStatusId")
    jira_status_mapping_id: Optional[str] = Field(alias="jiraStatusMappingId")
    jira_status_name: Optional[str] = Field(alias="jiraStatusName")


class QueryJiraStatusMappingProblemsJiraStatusMappingProblemsSpaceProblems(BaseModel):
    code: str
    detail: Optional[str]
    detected_at: Optional[str] = Field(alias="detectedAt")


QueryJiraStatusMappingProblems.model_rebuild()
QueryJiraStatusMappingProblemsJiraStatusMappingProblems.model_rebuild()
